#include<conio.h>
#include<iostream.h>
#include<cstring>
#include<fstream>
void highscore()
{
cout<<"                                   +hddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddh+"<<endl;
cout<<"                                   d                                                                                                  d"<<endl;
cout<<"                                   m  mmdhhhhhhhhhhhhdmmmmmdhhhhhhhhhhhhmmmmmdhddddddddddhdmmmmmmhddddddddddhdmmmmmmdhhhhhhhhhhhhdmm  d"<<endl;
cout<<"                                   d  dmhyyyyyyyyyyyyhmdddmyyyyyyyyyyyyyddddmdyyyyyyyyyyyyhmdddddyyyyyyyyyyyyymddddmhyyyyyyyyyyyydmd  d"<<endl;
cout<<"                                   m  mmhyys:.```-syyhmmmmNyyy+-```./yyymmmmmdyyy/.``.:oyyhmmmmmdyy-.....-+yyhNmmmmNhyy.``````:yydmm  d"<<endl;
cout<<"                                   m  mmhyy. .os- `yyhmmmmmyy+  /oo` -yymmmmmdyy. .oo: `oyhmmmmmdyy. .oo/  +yhNmmmmmhyy` :oooosyydmm  d"<<endl;
cout<<"                                   d  dmhhy` /hyyooyhhmdddmhh: .yhh+-:yhmmddmdys  +hyy` /yhmdddddhy. -hhy. -hhmddddmhyy` /hhyyyyhdmd  d"<<endl;
cout<<"                                   m  mmyyy: `:+syhhyymmmmmsy: .yhhhhhhydmmmmhso  +hhy` /hymmmmmhyy. -yy+` /hsmmmmmmsyy` :sssshhhhmm  d"<<endl;
cout<<"                                   d  dmhhhyo/:..-+hhymdddmyy/-:hhhhhhhhdmddmhys--ohhy--+dymddddhyy:-----:ohdymddddmyyy------/hhhhmd  d"<<endl;
cout<<"                                   m  mmhyyyyyyy/ `syhmmmmmyy: .yyyyyyyydmmmmhso` +yyy` /yymmmmmdyy.`-s. -yyyymmmmmmysy` /yyyyyyydmm  d"<<endl;
cout<<"                                   m  mmhys::syyo  oyhmmmmmyy: `yyy:`.yymmmmmdys` +yys` /yhmmmmmdyy. -ys` :yyhmmmmmmhyy` /yyyyyyydmm  d"<<endl;
cout<<"                                   d  dmhyy. .//. .yyhddddmyyo` -+/` /yyddddddyy- ./+- `syhmdddddyy. -hy+  +yhmddddmhyy` -////oyyddd  d"<<endl;
cout<<"                                   m  mmhhhy+:--:+yhhhdmmmmhyhs/---:oyhhdmmmmdhhy+-..-/shyhmmmmddhy/-/hhy/-:yhmmmmmmhyy:------/hhdmm  d"<<endl;
cout<<"                                   m  mmdhhhhhhhhhhhhddmmmmhhhhhhhhhhhhhdmmmmdhhhhhhhhhhhhhmmmmddhhhhhhhhhhhhhmmmmmmhhhhhhhhhhhhhdmm  d"<<endl;
cout<<"                                   d  dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd  d"<<endl;
cout<<"                                   m  mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm  d"<<endl;
cout<<"                                   m  mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm  d"<<endl;
cout<<"                                   d  ddmmmmmmmmmmmmmmdmddmmmmmmmmmmmmmmdmddmmmmmmmmmmmmmmmmddmddmmmmmmmmmmmmmddmddmmmmmmmmmmmmmmmdd  d"<<endl;
cout<<"                                   m  mmdyyyyyyyyyyyydmmmmmyyyyyyyyyyyyymmmmmdyyyyyyyyyyyyhmmmmmmyyyyyyyyyyyyhmmmmmmhyyyyyyyyyyyydmm  d"<<endl;
cout<<"                                   d  dmhys/////+syyydmdddmyyyyo///+syyymmddmdyyyyy//syyyyhmdddddyy+/////oyyyhmddddmhyo/////+syyydmd  d"<<endl;
cout<<"                                   m  mmdy+  .-.` :yydmmmmNyys. .-. `+yymmmmmdyyyy+  -yyyyhmmmmmdyy. `--` `oyhNmmmmmhy/  --. `/yydmm  d"<<endl;
cout<<"                                   m  mmdy+  oyy/ `sydmmmmNhy: `yyy: `yymmmmmdyyyy.  `syyyhNmmmmdyy. -yyy` :yhNmmmmmhy+ `syy/ `sydmm  d"<<endl;
cout<<"                                   d  dmdh+  oyy/ `shdmdddmhh- .yyh/ `yhmdddmmhyy+ `` :hyhdmddddmhy. -hyy` :hhmddddmdh+ `syyo  shdmd  d"<<endl;
cout<<"                                   m  mmohs--::---ohhommmmmoh/-:hdd+--hshmmmmysdd/-+o--hddommmmmyyh:-:++:-:ydommmmmmoyo--hdds--yhymm  d"<<endl;
cout<<"                                   m  mmdh+ `/++- `shdmmmmmhy- .syy: `shmmmmmdhs+ `os. :yhhmmmmmdhs. .:` :syhhmmmmmmhy/ `oyy+ `oddmm  d"<<endl;
cout<<"                                   d  dmhy+ `oyys  +yhmdddmyy- .yyy/ `yymdddmdyy- `..` `syhmdddddyy. -y/``oyyymddddmhy/ `syy+ `oydmd  d"<<endl;
cout<<"                                   m  mmdy+ `oys: `oydmmmmmyy/ `oys. .yymmmmmdyo` /+++` /yhmmmmddyy. -yy- `syhmmmmmmhy/ `syo. .yydmm  d"<<endl;
cout<<"                                   d  dmdyo     `.oyydddddmhyy:` ```-syymdddddy: .yyyy: `yhmdddddyy. -yyy. -yhmddddmhy+     `:syyddd  d"<<endl;
cout<<"                                   m  mmdhyyyyyyyhhhhddmmmmhhhhysssyhhhhmmmmmdyyyyhhhhyyyyhmmmmddhyyyyhhhyyyyhmmmmmmhhyyyyyyyhhhhdmm  d"<<endl;
cout<<"                                   m  mmddddddddddddddmmmmmddddddddddddddmmmmddddddddddddddmmmmmmdddddddddddddmmmmmmddddddddddddddmm  d"<<endl;
cout<<"                                   d  dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd  d"<<endl;
cout<<"                                   m  mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm  d"<<endl;
cout<<"                                   m                                                                                                  d"<<endl;
cout<<"                                   ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddyd"<<endl;
}
void lose()
{
cout<<"                                                                                                            `-`"<<endl;
cout<<"                                                                                                       .:/+o/+o"<<endl;
cout<<"                                                                                                 `-:+o+/-`    s/"<<endl;
cout<<"                                                                                            .-/+o+:.`         .y-"<<endl;
cout<<"                                                                                      `.:+o+/-.                -y`"<<endl;
cout<<"                                                                                 `-/+o+:-`                      +o"<<endl;
cout<<"                                                                           `.:+o+/:.              `-/+.          s/"<<endl;
cout<<"                                                                      `-/+o+:-`             `..`    -/           .y-"<<endl;
cout<<"                                                                 .:/oo/:.              ``./sy+       `.           :y`"<<endl;
cout<<"                                                           `-:+o+/-`             ```       oyy-       .`           +o"<<endl;
cout<<"                                                      .-/+o+:.`               -```.:so/.   `yyy`       -            s/"<<endl;
cout<<"                                                `.:+o+/-.              ..   .s.      +yy+   -yyo        -           .y-"<<endl;
cout<<"                                            ./+o+:-`               `.:y/   `yy.       +yyo   +yy/       -            :y`"<<endl;
cout<<"                                            .y-             .-/:`     :`   -yy/        syy.   oyy:     ..             +o"<<endl;
cout<<"                                             :y`         `.-+yyy/.    -    `yyy.       -yy.    :+o+:...               `s/"<<endl;
cout<<"                                              +o             `:syyo- `.     :yys.      `y+                             .y-"<<endl;
cout<<"                                              `s/               .+yyy+       .oyy-     :/                               :s`"<<endl;
cout<<"                                               .y-                `oyy:        `://-```                         `.:+.    +o"<<endl;
cout<<"                                                :y`                `syy.                                   `.`````./o`   `s/"<<endl;
cout<<"                                                 +o                 .yys-.``                          ``./yy/    -  `:    .y-"<<endl;
cout<<"                                                 `s/              `..-.                         `  /      oyy-   /.        :s`"<<endl;
cout<<"                                                  .y-                                       `.`` `-+/     .yys``-os`   -`   +o"<<endl;
cout<<"                                                   :s`                                     ./       ``     -yys`  ./   `o   `s/"<<endl;
cout<<"                                                    +o                          `.``.:++:. -y/-...----.     +yy/   ``  -y/   .y-"<<endl;
cout<<"                                                    `s/                        :o      :yyo`/yyyyyyyyyys.    syy-    `:o+:    :s`"<<endl;
cout<<"                                                     .y-             `        :y+       -yys` ........-oy`   .yys-....         +o"<<endl;
cout<<"                                                      :s`      `.:/.`         sys        /yy+ -.        s` ``.:-`              `s/"<<endl;
cout<<"                                                       +o    `..syy-          oyy/        syo  o/.    `..                    .-/oo`"<<endl;
cout<<"                                                       `s/      .yys`         -syy:       +y-  `o`.```                 `.:+o+/-."<<endl;
cout<<"                                                        .y.      -yyo         :.oyy/      o-                      `-/+o+:-`"<<endl;
cout<<"                                                         :s`      +yy/        :+ .:++:.``.                   .:+oo/:."<<endl;
cout<<"                                                          +o       syy-      `sy-                      `-/+o+/-`"<<endl;
cout<<"                                                          `s/      .yys`  `.-/-.                  .:/oo/:."<<endl;
cout<<"                                                           .y.      :ys/..`                 `-:+o+/-`"<<endl;
cout<<"                                                            :s`   `..                  .-/+o+:.`"<<endl;
cout<<"                                                             oo                  `.:+o+/-."<<endl;
cout<<"                                                             `s:            `-/+o+:-`"<<endl;
cout<<"                                                              .y.     `.:+o+/:."<<endl;
cout<<"                                                               :s.-/+o+/-`"<<endl;
cout<<"                                                                //:."<<endl;
}

void win()
{
cout<<"                                                     .........................................-.---------------------"<<endl;
cout<<"                                                     ............-..............................---------.......----."<<endl;
cout<<"                                                     `....       ...............................---------       ----`"<<endl;
cout<<"                                                      ....`      .--............................--------.      `----`"<<endl;
cout<<"                                                      `.-..      ...............................--------.      ----."<<endl;
cout<<"                                                       .-..`     ..-.  .........................--------.     .---."<<endl;
cout<<"                                                       `....`    `...  .........................--------.    .----`"<<endl;
cout<<"                                                        `....`   `-..  ........................---------`   .----`"<<endl;
cout<<"                                                         `.-...  `...  `.......................---------` `.----`"<<endl;
cout<<"                                                          `.....``...  `-......................---------``----.`"<<endl;
cout<<"                                                            `........` `--.....................--------------."<<endl;
cout<<"                                                             `.......` `.................---.----------:::::------:::::::`"<<endl;
cout<<"                                                              `.....```-------------:::::::::/:/:://////////////////////`"<<endl;
cout<<"                                                    ````````.....-:::::://////////////////////////:://///////////////////`"<<endl;
cout<<"                                           .----::::://////////////////////////////////////////////:////:-.:///-..-//////`"<<endl;
cout<<"                                           `-////////////////////////////////:-..`:////::--:///-..``:///`  :///.  .//////`"<<endl;
cout<<"                                             .://///////////////////////////.`    .//:`   `:///-     -//-  -////  .//////`"<<endl;
cout<<"                                               -///////////-.``///////////////`   .///:`  -/////`  `  -/:  .////. .//////`"<<endl;
cout<<"                                                .//////////-   -/////-..`.////-   .////.  ./////. `:`  ./` `////- `//////`"<<endl;
cout<<"                                                 `-/////////`  `:///:     -///-   -////-  `/////.  :/.  ..  ///// `//////`"<<endl;
cout<<"                                                   `:///////-   .///-     `://-   ://///   /////:  -//-     -////////////`"<<endl;
cout<<"                                                    `-///////.   ://`  .`  `//-   //////`  :////:  .///-    .////` `/////`"<<endl;
cout<<"                                                      .://////`  `//   ::   ./.  `//////.  ./////  `////-   `////:-://///`"<<endl;
cout<<"                                                       `-/////:   .:   //-   -`  .//////.  `.:///.../////:://////////////`"<<endl;
cout<<"                                                         `:////-   `  `///.      -/////-````.:///////////////////////"<<endl;
cout<<"                                                          ./////.     .////`     ////////////////////////////"<<endl;
cout<<"                                                        `-///////.    .////-   `-/////////////////////"<<endl;
cout<<"                                                       `://///////....://///::://///////////"<<endl;
cout<<"                                                      -/////////////:://///////////////"<<endl;
cout<<"                                                    `:////////////////////         ----"<<endl;
cout<<"                                                   .///////////////                ----"<<endl;
cout<<"                                                 `-///////                         ----"<<endl;
cout<<"                                                                                   ----"<<endl;
cout<<"                                                                                   ----"<<endl;
cout<<"                                                                                -..-----"<<endl;
cout<<"                                                                            .......-----"<<endl;
cout<<"                                                                           :-............-----"<<endl;
cout<<"                                                                         --................------"<<endl;
cout<<"                                                                       ......................------"<<endl;
cout<<"\t\t\t\t\t\t\t\t    you become radja and win this game!"<<endl;
}

void nuki()
{
system("color 0A");
cout<<"                                                                                                                                                                       "<<endl;
cout<<"                                                                                                                                                                       "<<endl;
cout<<"                                                                                                                                                                       "<<endl;
cout<<"                                                                                                                                                                       "<<endl;
cout<<"            oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo           "<<endl;
cout<<"            hh+//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////+hh           "<<endl;
cout<<"            hh-                                                                                                                                          -hh           "<<endl;
cout<<"            hh-                                                                                                                                          -hh           "<<endl;
cout<<"            hh-                                                                                                                                          -hh           "<<endl;
cout<<"            hh-                                                                                                                                          -hh           "<<endl;
cout<<"            hh-                                                                                                                                          -hh           "<<endl;
cout<<"            hh-                                                                                                                                          -hh           "<<endl;
cout<<"            hh-                                                                                                                                          -hh           "<<endl;
cout<<"            hh-                                                                                                                                          -hh           "<<endl;
cout<<"            hh-                                                                             .           .-`                                              -hh           "<<endl;
cout<<"            hh-                                             :/sss-   -/s+:               -ohh.          yh+                                              -hh           "<<endl;
cout<<"            hh-                                              .hohh+    h-`               `/hh           .-`                                              -hh           "<<endl;
cout<<"            hh-                                              .h  yhy:  h-`  :/+o  :/++   `/hh  :oo/-   :/++                                              -hh           "<<endl;
cout<<"            hh-                                              .h.  +hho h-`  `ohh  .yhs   `/hh :o/.     .yhs                                              -hh           "<<endl;
cout<<"            hh-                                              .h.   .shhh-`  `/hh  `sho   `/hhohy/      `sho                                              -hh           "<<endl;
cout<<"            hh-                                              .h.     /yh-`  `:hh/ .yhs   `/hh.-shy:    `yhs                                              -hh           "<<endl;
cout<<"            hh-                                             :+++:     .+-`   `:oo+:+++:  :++o/  ooo/-  /o++/                                             -hh           "<<endl;
cout<<"            hh-                                                                                                                                          -hh           "<<endl;
cout<<"            hh-                                                                                                                                          -hh           "<<endl;
cout<<"            hh-                                                                                                                                          -hh           "<<endl;
cout<<"            hh-                                                                                                                                          -hh           "<<endl;
cout<<"            hh-                                                                                                                                          -hh           "<<endl;
cout<<"            hh-                                                                                                                                          -hh           "<<endl;
cout<<"            hh-                                                               /s/`.ss.`/s/                                                               -hh           "<<endl;
cout<<"            hh-                                                               +hyoohhooyh+                                                               -hh           "<<endl;
cout<<"            hh-                                                               +yyyyyyyyyy+                                                               -hh           "<<endl;
cout<<"            hh-                                                               -//////////-                                                               -hh           "<<endl;
cout<<"            hh/---------------------------------------------------            /ooshhhhsoo/            ---------------------------------------------------/hh           "<<endl;
cout<<"            ssssssssssssssssssssssssssssssssssssssssssssssssssssss               +hhhh+               ssssssssssssssssssssssssssssssssssssssssssssssssssssss           "<<endl;
cout<<"                                                                              -shhhhhhhhs-                                                                             "<<endl;
cout<<"                                                                            --://////////:--                                                                           "<<endl;
cout<<"                                                                            oyhhhhhhhhhhhhyo                                                                           "<<endl;
cout<<"                                                                            -yhhhhhhhhhhhhy-                                                                           "<<endl;
cout<<"                                                                           -yyyyyyyyyyyyyyyy-                                                                          "<<endl;
cout<<"                                                                                                                                                                       "<<endl;
cout<<"                                                                        Press Any Key to Continue                                                                       "<<endl;
cout<<"                                                                                                                                                                       "<<endl;
cout<<"                                                                                                                                                                       "<<endl;
cout<<"                                                                                                                                                                       "<<endl;
getch();
}
void semutvssemut()
{
cout<<"                 `-.                              .-`"<<"                                                   `-.                              .-`"<<endl;
cout<<"                   `-`                          `-`"<<"                                                        `-`                          `-`"<<endl;
cout<<"                     -.                        .-"<<"                                                            -.                        .-"<<endl;
cout<<"                      -.                      .-"<<"                                                              -.                      .-"<<endl;
cout<<"                       :.                    .:"<<"                                                                :.                    .:"<<endl;
cout<<"                        :.                  .:"<<"                                                                  :.                  .:"<<endl;
cout<<"                         ::`              `::"<<"                                                                    ::`              `:: "<<endl;
cout<<"                          `::-` `-`.-` `-::`"<<"                                                                      `::-` `-`.-` `-::`"<<endl;
cout<<"              .              `:/hy//yy/:`              ."<<"                                               .              `:/hy//yy/:`              ."<<endl;
cout<<"              .-`             .yhhdddhy.             `-."<<"                                               .-`             .yhhdddhy.             `-."<<endl;
cout<<"                ..``         .hhhhhhhhhy`         `..."<<"                                                   ..``         .hhhhhhhhhy`         `...  "<<endl;
cout<<"                   .-        yhhhhhhhhhhs        -."<<"                                                         .-        yhhhhhhhhhhs        -. "<<endl;
cout<<"                     :.     `hyoooyyhhyyh      .:"<<"                                                             :.     `hyoooyyhhyyh       .:"<<endl;
cout<<"                      /-     shhhhhhhhhho     -/"<<"                             .s: .smmmdy+```"<<"                   /-     shhhhhhhhhho     -/"<<endl;
cout<<"                       +-     `./hddh/.`     -+"<<"                  . :         `ydh+NNmo."<<"                         +-     `./hddh/.`     -+"<<endl;
cout<<"                        +.     shyyhhho     .+"<<"                   -/:+.       -ddmMNm-"<<"                            +.     shyyhhho     .+"<<endl;
cout<<"                         ++`   yhhhhhhs   `++"<<"                    `os+s.      +dmNMNh"<<"                              ++`   yhhhhhhs   `++"<<endl;
cout<<"                          -s+` -ddhddd- `+s-"<<"                      .syss-     ymmdMNN/"<<"                              -s+` -ddhddd- `+s-"<<endl;
cout<<"                            :o+ohhhhhho+o:"<<"                         :yhyy-   -mmm.oNNmdso/:."<<"                          :o+ohhhhhho+o:"<<endl;
cout<<"                                shyhho"<<"                              :hddh-  ymmh  -sdmmmddhy/`"<<"                           shyhho"<<endl;
cout<<"                 `-...--...`   `dddddh    `...--...-`"<<"                /dmmd--mNN:     .-:+hdhhs."<<"           `-...--...`   `dddddh    `...--...-`"<<endl;
cout<<"             `-::----://++o++//sdyyhhds//++o++//:----::-`"<<"             /dmmddNNd           /hhhs"<<"       `-::----://++o++//sdyyhhds//++o++//:----::-`"<<endl;
cout<<"          `:::`                -hhhhhh-                .:::`"<<"           :dNNNNN+           -hhhy"<<"    `:::`                -hhhhhh-                .:::`"<<endl;
cout<<"       `....                `-oy+ohh++yo-`                ....`"<<"         -dNNNm`          -yhhy:"<<"    `....             `-oy+ohh++yo-`             ....`"<<endl;
cout<<"   ```...`            .:///:-.   -hh.   .-:///:.            `...```"<<"      -dMMo   `  .`.-ohhhy/"<<"    ````      -+s/-`      -sdhdds.      `-/s+-      ```` "<<endl;
cout<<"    ````           -+s/-`      -sdhdds.      `-/s+-           ````"<<"        .dN`    .-sddddhy+."<<"            .+o/.        `ohhdhddhh+         ./o+."<<endl;
cout<<"                .+o/.        `ohhdhddhh+         ./o+."<<"                     `+      `-/++:-`"<<"           -//:`           sdhhhddhhhdo           `://-"<<endl;
cout<<"             -//:`           sdhhhddhhhdo           `://-"<<"                                            ::`             :dddhshdddddd.             `::"<<endl;
cout<<"            ::`             :dddhshdddddd.             `::"<<"                                          `/               +dhhdddddddhd:               /`"<<endl;
cout<<"           `/               +dhhdddddddhd:               /`"<<"                                         -/               :dhhhhddhhhhd-               /-"<<endl;
cout<<"           -/               :dhhhhddhhhhd-               /-"<<"                                         /-                sddhhhhhdddo                -/"<<endl;
cout<<"           /-                sddhhhhhdddo                -/"<<"                                         /-                 /hdhddddh:                 -/"<<endl;
cout<<"           /-                 /hdhddddh:                 -/"<<"                                         :                    -/++/.                    :"<<endl;
cout<<"           :                    -/++/.                    :"<<"                                         `-                                              -`"<<endl;
cout<<"          `-                                              -`"<<"                                        -`                                              `-"<<endl;
cout<<"          -`                                              `-"<<"                                        -                                                -"<<endl;
cout<<"          -                                                -"<<"                                        -                                                -"<<endl;
cout<<"          -                                                -"<<"                                        :                                                :"<<endl;
cout<<"         :                                                :"<<"                                         :                                                :"<<endl;
cout<<"         -`                                                `-"<<"                                       -`                                                `-"<<endl;
}

void semutvsmanusia()
{
cout<<"                 `-.                              .-`"<<"                                                                          `.---.```"<<endl;
cout<<"                   `-`                          `-`"<<"                                                                       ./shmmmmmmmmmmdys+-"<<endl;
cout<<"                     -.                        .-"<<"                                                                      `+hdmNmmmmmmmmmNNNNNmmdo."<<endl;
cout<<"                      -.                      .-"<<"                                                                     -ommmmmmNNNmmmmmmmmmNNNNNmd/"<<endl;
cout<<"                       :.                    .:"<<"                                                                   :ymmNmmmmNmmNmmmmmNNNNNNNNNNmmho-"<<endl;
cout<<"                        :.                  .:"<<"                                                                    -dmmmNNmNNmmmmmmmmmmmmNNNNNNNNmddds."<<endl;
cout<<"                         ::`              `::"<<"                                                                     /mmmmmmNNmmmmmNmmmddmmNNNNNNNNmmmdmd-"<<endl;
cout<<"                          `::-` `-`.-` `-::`"<<"                                                                     -mmNNmdyhdmNNNNmmdddmmmNNNNNmmmddddmmd:"<<endl;
cout<<"              .              `:/hy//yy/:`              ."<<"                                                        `hmmmmds//+oyhddddhhhddddddddhhhyyydmNNm-"<<endl;
cout<<"              .-`             .yhhdddhy.             `-."<<"                                                       .ymmmmdy+/::::::::::://+++++++//++oohmmNmo"<<endl;
cout<<"                ..``         .hhhhhhhhhy`         `..."<<"                                                         /dmNmmhs+/:::::-------------:::///++smmNms"<<endl;
cout<<"                   .-        yhhhhhhhhhhs        -."<<"                                                            -dmmmds+//::::---------------::///++odmNm:"<<endl;
cout<<"                     :.     `hyoooyyhhyyh      .:"<<"                                                            ::-ddmdy+////::::---::--:::::::::///++sdmNd."<<endl;
cout<<"                      /-     shhhhhhhhhho     -/"<<"                              .s: .smmmdy+```"<<"                //:+dmho//////:::-----:::::::::::///++odmmy"<<endl;
cout<<"                       +-     `./hddh/.`     -+"<<"                   . :         `ydh+NNmo."<<"                     .::/hdo////+sss+/:-----:::--:::::/+oooohmdo"<<endl;
cout<<"                        +.     shyyhhho     .+"<<"                    -/:+.       -ddmMNm-"<<"                        -:/hh/://+ossyhhs+/::-::::::::+syhhhy+ydy/"<<endl;
cout<<"                         ++`   yhhhhhhs   `++"<<"                     `os+s.      +dmNMNh"<<"                         --:os/:://+ooyysyyys/:::://+oyyyysssy+yy/`"<<endl;
cout<<"                          -s+` -ddhddd- `+s-"<<"                       .syss-     ymmdMNN/"<<"                        -::////::/++/oo//oos+:::/ossoyys/osoo+h:"<<endl;
cout<<"                            :o+ohhhhhho+o:"<<"                          :yhyy-   -mmm.oNNmdso/:."<<"                  .-:////::::::::://///:::/ooo/+o/:+o++++"<<endl;
cout<<"                                shyhho"<<"                               :hddh-  ymmh  -sdmmmddhy/`"<<"               `-::///:::------:::::::::++/::///+++++"<<endl;
cout<<"                 `-...--...`   `dddddh    `...--...-`"<<"                 /dmmd--mNN:     .-:+hdhhs."<<"                ``.///::-----::/:::::::+++/::::/+++/"<<endl;
cout<<"             `-::----://++o++//sdyyhhds//++o++//:----::-`"<<"              /dmmddNNd           /hhhs"<<"                  `///:::-:://///:::---/+++/:::///-`"<<endl;
cout<<"          `:::`                -hhhhhh-                .:::`"<<"            :dNNNNN+           -hhhy"<<"                 .:+//////+++//+oo+/:::+oo++//////"<<endl;
cout<<"       `....                `-oy+ohh++yo-`                ....`"<<"          -dNNNm`          -yhhy:"<<"               `/yds+//+/+oso++//+oo++osssoo++/++:"<<endl;
cout<<"   ```...`            .:///:-.   -hh.   .-:///:.            `...```"<<"       -dMMo   `  .`.-ohhhy/"<<"              `:oyhy-/++//+o+ooo++/++ossssyyso++++`"<<endl;
cout<<"    ````           -+s/-`      -sdhdds.      `-/s+-           ````"<<"         .dN`    .-sddddhy+."<<"            `:+oyys+-./o+++////++++++oossssso+++os-"<<endl;
cout<<"                .+o/.        `ohhdhddhh+         ./o+."<<"                      `+      `-/++:-`"<<"           `./ossssso-...+ooo+/////+++++oooooo++oshdyo:`"<<endl;
cout<<"             -//:`           sdhhhddhhhdo           `://-"<<"                                           `-:+sssssyyss/..```-++o+/////://///+++++osyddhyys+:`"<<endl;
cout<<"            ::`             :dddhshdddddd.             `::"<<"                                          sssysssssssss:`.`````-:++++///////++++///soyhhhhyhhyo/.`"<<endl;
cout<<"           `/               +dhhdddddddhd:               /`"<<"                                         ssyssysssysso:`````````.-/++ooooooo/::://++shhhhhyhhhhyso/-`"<<endl;
cout<<"           -/               :dhhhhddhhhhd-               /-"<<"                                         yyssssssyysss/````````````.:+sss+:--::://++shhhhhhhyhhhyyyyy"<<endl;
cout<<"           /-                sddhhhhhdddo                -/"<<"                                         yssssssssssss+`````     ````-+ss-..--::::/:syyhhhhyyyhhhhyyy"<<endl;
cout<<"           /-                 /hdhddddh:                 -/"<<"                                         ysssssssssssso.``         `-hddmd:...------syyyyyyyyyyyhhyyy"<<endl;
cout<<"           :                    -/++/.                    :"<<"                                         ssssssssssssss:`          `-ydddd/........-sssyyyyyyyyyyyyyy"<<endl;
cout<<"          `-                                              -`"<<"                                        ysssssssssssos+``        ...+mddo--.......:syyyyyyyyyyyyyyyy"<<endl;
cout<<"          -`                                              `-"<<"                                        yhyssssssssssos-` ```   ````+dhd.```.``.../ssyyyyyyyyyhhhyys"<<endl;
cout<<"          -                                                -"<<"                                        sssyysssssyssss+``` `` ``` -hhhd/`````.```osyyyyyyyyhhyyyyyy"<<endl;
cout<<"          -                                                -"<<"                                        yyyssyssssssssso.````````` yyhhdh````````.ssyyyyyyyyyyyyyyys"<<endl;
cout<<"         :                                                :"<<"                                         ssssssssssssssss/`````````.hhhhdd:```````:sssyyyysyyyyyyyyyy"<<endl;
cout<<"         -`                                                `-"<<"                                       sssssssssssssssss/`````````.hhhhhddd:```:sssyyyysyyyyyyyyyy"<<endl;
}

void semutvsgajah()
{
cout<<"                 `-.                              .-`"<<"                                                                    `:+syyyyssso+:`"<<endl;
cout<<"                   `-`                          `-`"<<"                                                                   :shs/-`       .:odh+` "<<endl;
cout<<"                     -.                        .-"<<"                                                        .:/+++/-`  /mh:                -ym/     .---."<<endl;
cout<<"                      -.                      .-"<<"                                                       odms+/:::+syhNs     `-       .     +N:/ohdddmNNNh-"<<endl;
cout<<"                       :.                    .:"<<"                                                        `om.        dd     /o`       +/.    hNs:`     `N/"<<endl;
cout<<"                        :.                  .:"<<"                                                           mh        hs  `/+.                ss        /N"<<endl;
cout<<"                         ::`              `::"<<"                                                            mm        om      `:+++++oos+`    m/        yN`"<<endl;
cout<<"                          `::-` `-`.-` `-::`"<<"                                                            .Nd        oN     .:. `.-:::-.    -N:        oN:"<<endl;
cout<<"              .              `:/hy//yy/:`              ."<<"                                                /Ns       .m/o`      --:::---:-   `N:        :Ns"<<endl;
cout<<"              .-`             .yhhdddhy.             `-."<<"                                                sN:       sd dy      ://////:`   :/m:        .Ny"<<endl;
cout<<"                ..``         .hhhhhhhhhy`         `..."<<"                                                  hN`       :N/`h       `--:::     mdd         .No"<<endl;
cout<<"                   .-        yhhhhhhhhhhs        -."<<"                                                     sh         /myo         -//.     mNo         yh`"<<endl;
cout<<"                     :.     `hyoooyyhhyyh      .:"<<"                                                       -h         /mo          .:`      +Ny        sd`"<<endl;
cout<<"                      /-     shhhhhhhhhho     -/"<<"                              .s: .smmmdy+```"<<"            h:       :N+                     :N+      ym."<<endl;
cout<<"                       +-     `./hddh/.`     -+"<<"                   . :         `ydh+NNmo."<<"                 .d.   `/omN`.`       `//:`     `.`dhy+`  sm."<<endl;
cout<<"                        +.     shyyhhho     .+"<<"                    -/:+.       -ddmMNm-"<<"                    -d:-hy/`+Nhmsy.             .ss/yN- /m+-N:"<<endl;
cout<<"                         ++`   yhhhhhhs   `++"<<"                     `os+s.      +dmNMNh"<<"                      .hN/    :mo :N/    `--.   `mN+ `N:  .ohs"<<endl;
cout<<"                          -s+` -ddhddd- `+s-"<<"                       .syss-     ymmdMNN/"<<"                       `      m. :dN:     ``   :NhN- mo"<<endl;
cout<<"                            :o+ohhhhhho+o:"<<"                          :yhyy-   -mmm.oNNmdso/:."<<"                        N` d:sm`   -..`  +N+ys mo"<<endl;
cout<<"                                shyhho"<<"                               :hddh-  ymmh  -sdmmmddhy/`"<<"                     d:-N``m+         oN/+h-N:"<<endl;
cout<<"                 `-...--...`   `dddddh    `...--...-`"<<"                 /dmmd--mNN:     .-:+hdhhs."<<"                    /h/d  sh   -::-  +N:/hyd"<<endl;
cout<<"             `-::----://++o++//sdyyhhds//++o++//:----::-`"<<"              /dmmddNNd           /hhhs"<<"                     +yh  +m  -//:`  yN-sNy."<<endl;
cout<<"          `:::`                -hhhhhh-                .:::`"<<"            :dNNNNN+           -hhhy"<<"                          sm  `+o+/ .NN` "<<endl;
cout<<"       `....                `-oy+ohh++yo-`                ....`"<<"          -dNNNm`          -yhhy:"<<"                         `ms   .:/. yN+"<<endl;
cout<<"   ```...`            .:///:-.   -hh.   .-:///:.            `...```"<<"       -dMMo   `  .`.-ohhhy/"<<"                         .hs   --.` +Ns"<<endl;
cout<<"    ````           -+s/-`      -sdhdds.      `-/s+-           ````"<<"         .dN`    .-sddddhy+."<<"                         +m/  ./:.` +Ns"<<endl;
cout<<"                .+o/.        `ohhdhddhh+         ./o+."<<"                      `+      `-/++:-`"<<"                         .hd- .-  `` oNo"<<endl;
cout<<"             -//:`           sdhhhddhhhdo           `://-"<<"                                                        `-:+Ny`   .:-``hm/"<<endl;
cout<<"            ::`             :dddhshdddddd.             `::"<<"                                                      .d:+Ny   ::-  /my."<<endl;
cout<<"           `/               +dhhdddddddhd:               /`"<<"                                                    .y:+Nd`:`    :hh-"<<endl;
cout<<"           -/               :dhhhhddhhhhd-               /-"<<"                                                    h- :N: `-- :hymo"<<endl;
cout<<"           /-                sddhhhhhdddo                -/"<<"                                                    h- :N: `-- :hymo"<<endl;
cout<<"           /-                 /hdhddddh:                 -/"<<"                                                    h- :N: `-- :hymo"<<endl;
cout<<"           :                    -/++/.                    :"<<"                                                    s+/sN/-. `hmm.m+"<<endl;
cout<<"          `-                                              -`"<<"                                                    `+mN:   -:.`sm`"<<endl;
cout<<"          -`                                              `-"<<"                                                    `+mN:   -:.`sm`"<<endl;
cout<<"          -                                                -"<<"                                                      `yd:`  `/hh."<<endl;
cout<<"          -                                                -"<<"                                                      `yd:`  `/hh."<<endl;
cout<<"         :                                                :"<<"                                                         /yyssys:"<<endl;
cout<<"         -`                                                `-"<<"                                                          ss:"<<endl;
}

void manusiavssemut()
{
cout<<"                            `.---.```"<<"                                                                                    `-.                              .-`"<<endl;
cout<<"                       ./shmmmmmmmmmmdys+-"<<"                                                                                  `-`                          `-`"<<endl;
cout<<"                    `+hdmNmmmmmmmmmNNNNNmmdo."<<"                                                                                 -.                        .-"<<endl;
cout<<"                  -ommmmmmNNNmmmmmmmmmNNNNNmd/"<<"                                                                                 -.                      .-"<<endl;
cout<<"               :ymmNmmmmNmmNmmmmmNNNNNNNNNNmmho-"<<"                                                                                :.                    .:"<<endl;
cout<<"               -dmmmNNmNNmmmmmmmmmmmmNNNNNNNNmddds."<<"                                                                              :.                  .:"<<endl;
cout<<"               /mmmmmmNNmmmmmNmmmddmmNNNNNNNNmmmdmd-"<<"                                                                              ::`              `::"<<endl;
cout<<"              -mmNNmdyhdmNNNNmmdddmmmNNNNNmmmddddmmd:"<<"                                                                              `::-` `-`.-` `-::`"<<endl;
cout<<"             `hmmmmds//+oyhddddhhhddddddddhhhyyydmNNm-"<<"                                                                  .              `:/hy//yy/:`              ."<<endl;
cout<<"            .ymmmmdy+/::::::::::://+++++++//++oohmmNmo"<<"                                                                  .-`             .yhhdddhy.             `-."<<endl;
cout<<"            /dmNmmhs+/:::::-------------:::///++smmNms"<<"                                                                    ..``         .hhhhhhhhhy`         `..."<<endl;
cout<<"            -dmmmds+//::::---------------::///++odmNm:"<<"                                                                       .-        yhhhhhhhhhhs        -."<<endl;
cout<<"          ::-ddmdy+////::::---::--:::::::::///++sdmNd."<<"                                                                         :.     `hyoooyyhhyyh       .:"<<endl;
cout<<"          //:+dmho//////:::-----:::::::::::///++odmmy"<<"                               .s: .smmmdy+```"<<"                             /-     shhhhhhhhhho     -/"<<endl;
cout<<"          .::/hdo////+sss+/:-----:::--:::::/+oooohmdo"<<"                  . :         `ydh+NNmo."<<"                                    +-     `./hddh/.`     -+"<<endl;
cout<<"           -:/hh/://+ossyhhs+/::-::::::::+syhhhy+ydy/"<<"                  -/:+.       -ddmMNm-"<<"                                       +.     shyyhhho     .+"<<endl;
cout<<"           --:os/:://+ooyysyyys/:::://+oyyyysssy+yy/`"<<"                  `os+s.      +dmNMNh"<<"                                         ++`   yhhhhhhs   `++"<<endl;
cout<<"           -::////::/++/oo//oos+:::/ossoyys/osoo+h:"<<"                     .syss-     ymmdMNN/"<<"                                         -s+` -ddhddd- `+s-"<<endl;
cout<<"           .-:////::::::::://///:::/ooo/+o/:+o++++"<<"                       :yhyy-   -mmm.oNNmdso/:."<<"                                     :o+ohhhhhho+o:"<<endl;
cout<<"           `-::///:::------:::::::::++/::///+++++"<<"                         :hddh-  ymmh  -sdmmmddhy/`"<<"                                      shyhho"<<endl;
cout<<"             ``.///::-----::/:::::::+++/::::/+++/"<<"                          /dmmd--mNN:     .-:+hdhhs."<<"                      `-...--...`   `dddddh    `...--...-`"<<endl;
cout<<"               `///:::-:://///:::---/+++/:::///-`"<<"                           /dmmddNNd           /hhhs"<<"                  `-::----://++o++//sdyyhhds//++o++//:----::-`"<<endl;
cout<<"              .:+//////+++//+oo+/:::+oo++//////"<<"                              :dNNNNN+           -hhhy"<<"               `:::`                -hhhhhh-                .:::`"<<endl;
cout<<"            `/yds+//+/+oso++//+oo++osssoo++/++:"<<"                               -dNNNm`          -yhhy:"<<"               `....             `-oy+ohh++yo-`             ....`"<<endl;
cout<<"          `:oyhy-/++//+o+ooo++/++ossssyyso++++`"<<"                                -dMMo   `  .`.-ohhhy/"<<"               ````      -+s/-`      -sdhdds.      `-/s+-      ````"<<endl;
cout<<"       `:+oyys+-./o+++////++++++oossssso+++os-"<<"                                  .dN`    .-sddddhy+."<<"                       .+o/.        `ohhdhddhh+         ./o+."<<endl;
cout<<"    `./ossssso-...+ooo+/////+++++oooooo++oshdyo:`"<<"                                `+      `-/++:-`"<<"                      -//:`           sdhhhddhhhdo           `://-"<<endl;
cout<<"`-:+sssssyyss/..```-++o+/////://///+++++osyddhyys+:`"<<"                                                                  ::`             :dddhshdddddd.             `::"<<endl;
cout<<"sssysssssssss:`.`````-:++++///////++++///soyhhhhyhhyo/.`"<<"                                                             `/               +dhhdddddddhd:               /`"<<endl;
cout<<"ssyssysssysso:`````````.-/++ooooooo/::://++shhhhhyhhhhyso/-`"<<"                                                         -/               :dhhhhddhhhhd-               /-"<<endl;
cout<<"yyssssssyysss/````````````.:+sss+:--::://++shhhhhhhyhhhyyyyy"<<"                                                         /-                sddhhhhhdddo                -/"<<endl;
cout<<"yssssssssssss+`````     ````-+ss-..--::::/:syyhhhhyyyhhhhyyy"<<"                                                         /-                 /hdhddddh:                 -/"<<endl;
cout<<"ysssssssssssso.``         `-hddmd:...------syyyyyyyyyyyhhyyy"<<"                                                         :                    -/++/.                    :"<<endl;
cout<<"ssssssssssssss:`          `-ydddd/........-sssyyyyyyyyyyyyyy"<<"                                                        `-                                              -`"<<endl;
cout<<"ysssssssssssos+``        ...+mddo--.......:syyyyyyyyyyyyyyyy"<<"                                                        -`                                              `-"<<endl;
cout<<"yhyssssssssssos-` ```   ````+dhd.```.``.../ssyyyyyyyyyhhhyys"<<"                                                        -                                                -"<<endl;
cout<<"sssyysssssyssss+``` `` ``` -hhhd/`````.```osyyyyyyyyhhyyyyyy"<<"                                                        -                                                -"<<endl;
cout<<"yyyssyssssssssso.````````` yyhhdh````````.ssyyyyyyyyyyyyyyys"<<"                                                        :                                                :"<<endl;
cout<<"ssssssssssssssss/`````````.hhhhdd:```````:sssyyyysyyyyyyyyyy"<<"                                                       -`                                                `-"<<endl;
}

void manusiavsmanusia()
{
cout<<"                            `.---.```"<<"                                                                                          `.---.```"<<endl;
cout<<"                       ./shmmmmmmmmmmdys+-"<<"                                                                                ./shmmmmmmmmmmdys+-"<<endl;
cout<<"                    `+hdmNmmmmmmmmmNNNNNmmdo."<<"                                                                          `+hdmNmmmmmmmmmNNNNNmmdo."<<endl;
cout<<"                  -ommmmmmNNNmmmmmmmmmNNNNNmd/"<<"                                                                       -ommmmmmNNNmmmmmmmmmNNNNNmd/"<<endl;
cout<<"               :ymmNmmmmNmmNmmmmmNNNNNNNNNNmmho-"<<"                                                                  :ymmNmmmmNmmNmmmmmNNNNNNNNNNmmho-"<<endl;
cout<<"               -dmmmNNmNNmmmmmmmmmmmmNNNNNNNNmddds."<<"                                                               -dmmmNNmNNmmmmmmmmmmmmNNNNNNNNmddds."<<endl;
cout<<"               /mmmmmmNNmmmmmNmmmddmmNNNNNNNNmmmdmd-"<<"                                                              /mmmmmmNNmmmmmNmmmddmmNNNNNNNNmmmdmd-"<<endl;
cout<<"              -mmNNmdyhdmNNNNmmdddmmmNNNNNmmmddddmmd:"<<"                                                            -mmNNmdyhdmNNNNmmdddmmmNNNNNmmmddddmmd:"<<endl;
cout<<"             `hmmmmds//+oyhddddhhhddddddddhhhyyydmNNm-"<<"                                                          `hmmmmds//+oyhddddhhhddddddddhhhyyydmNNm-"<<endl;
cout<<"            .ymmmmdy+/::::::::::://+++++++//++oohmmNmo"<<"                                                         .ymmmmdy+/::::::::::://+++++++//++oohmmNmo"<<endl;
cout<<"            /dmNmmhs+/:::::-------------:::///++smmNms"<<"                                                         /dmNmmhs+/:::::-------------:::///++smmNms"<<endl;
cout<<"            -dmmmds+//::::---------------::///++odmNm:"<<"                                                         -dmmmds+//::::---------------::///++odmNm:"<<endl;
cout<<"          ::-ddmdy+////::::---::--:::::::::///++sdmNd."<<"                                                       ::-ddmdy+////::::---::--:::::::::///++sdmNd."<<endl;
cout<<"          //:+dmho//////:::-----:::::::::::///++odmmy"<<"                          .s: .smmmdy+```"<<"               //:+dmho//////:::-----:::::::::::///++odmmy"<<endl;
cout<<"          .::/hdo////+sss+/:-----:::--:::::/+oooohmdo"<<"             . :         `ydh+NNmo."<<"                     .::/hdo////+sss+/:-----:::--:::::/+oooohmdo"<<endl;
cout<<"           -:/hh/://+ossyhhs+/::-::::::::+syhhhy+ydy/"<<"             -/:+.       -ddmMNm-"<<"                        -:/hh/://+ossyhhs+/::-::::::::+syhhhy+ydy/"<<endl;
cout<<"           --:os/:://+ooyysyyys/:::://+oyyyysssy+yy/`"<<"             `os+s.      +dmNMNh"<<"                         --:os/:://+ooyysyyys/:::://+oyyyysssy+yy/`"<<endl;
cout<<"           -::////::/++/oo//oos+:::/ossoyys/osoo+h:"<<"                .syss-     ymmdMNN/"<<"                        -::////::/++/oo//oos+:::/ossoyys/osoo+h:"<<endl;
cout<<"           .-:////::::::::://///:::/ooo/+o/:+o++++"<<"                  :yhyy-   -mmm.oNNmdso/:."<<"                  .-:////::::::::://///:::/ooo/+o/:+o++++"<<endl;
cout<<"           `-::///:::------:::::::::++/::///+++++"<<"                    :hddh-  ymmh  -sdmmmddhy/`"<<"               `-::///:::------:::::::::++/::///+++++"<<endl;
cout<<"             ``.///::-----::/:::::::+++/::::/+++/"<<"                     /dmmd--mNN:     .-:+hdhhs."<<"                ``.///::-----::/:::::::+++/::::/+++/"<<endl;
cout<<"               `///:::-:://///:::---/+++/:::///-`"<<"                      /dmmddNNd           /hhhs"<<"                  `///:::-:://///:::---/+++/:::///-`"<<endl;
cout<<"              .:+//////+++//+oo+/:::+oo++//////"<<"                         :dNNNNN+           -hhhy"<<"                 .:+//////+++//+oo+/:::+oo++//////"<<endl;
cout<<"            `/yds+//+/+oso++//+oo++osssoo++/++:"<<"                          -dNNNm`          -yhhy:"<<"               `/yds+//+/+oso++//+oo++osssoo++/++:"<<endl;
cout<<"          `:oyhy-/++//+o+ooo++/++ossssyyso++++`"<<"                           -dMMo   `  .`.-ohhhy/"<<"              `:oyhy-/++//+o+ooo++/++ossssyyso++++`"<<endl;
cout<<"       `:+oyys+-./o+++////++++++oossssso+++os-"<<"                             .dN`    .-sddddhy+."<<"            `:+oyys+-./o+++////++++++oossssso+++os-"<<endl;
cout<<"    `./ossssso-...+ooo+/////+++++oooooo++oshdyo:`"<<"                           `+      `-/++:-`"<<"           `./ossssso-...+ooo+/////+++++oooooo++oshdyo:`"<<endl;
cout<<"`-:+sssssyyss/..```-++o+/////://///+++++osyddhyys+:`"<<"                                               `-:+sssssyyss/..```-++o+/////://///+++++osyddhyys+:`"<<endl;
cout<<"sssysssssssss:`.`````-:++++///////++++///soyhhhhyhhyo/.`"<<"                                           sssysssssssss:`.`````-:++++///////++++///soyhhhhyhhyo/.`"<<endl;
cout<<"ssyssysssysso:`````````.-/++ooooooo/::://++shhhhhyhhhhyso/-`"<<"                                       ssyssysssysso:`````````.-/++ooooooo/::://++shhhhhyhhhhyso/-`"<<endl;
cout<<"yyssssssyysss/````````````.:+sss+:--::://++shhhhhhhyhhhyyyyy"<<"                                       yyssssssyysss/````````````.:+sss+:--::://++shhhhhhhyhhhyyyyy"<<endl;
cout<<"yssssssssssss+`````     ````-+ss-..--::::/:syyhhhhyyyhhhhyyy"<<"                                       yssssssssssss+`````     ````-+ss-..--::::/:syyhhhhyyyhhhhyyy"<<endl;
cout<<"ysssssssssssso.``         `-hddmd:...------syyyyyyyyyyyhhyyy"<<"                                       ysssssssssssso.``         `-hddmd:...------syyyyyyyyyyyhhyyy"<<endl;
cout<<"ssssssssssssss:`          `-ydddd/........-sssyyyyyyyyyyyyyy"<<"                                       ssssssssssssss:`          `-ydddd/........-sssyyyyyyyyyyyyyy"<<endl;
cout<<"ysssssssssssos+``        ...+mddo--.......:syyyyyyyyyyyyyyyy"<<"                                       ysssssssssssos+``        ...+mddo--.......:syyyyyyyyyyyyyyyy"<<endl;
cout<<"yhyssssssssssos-` ```   ````+dhd.```.``.../ssyyyyyyyyyhhhyys"<<"                                       yhyssssssssssos-` ```   ````+dhd.```.``.../ssyyyyyyyyyhhhyys"<<endl;
cout<<"sssyysssssyssss+``` `` ``` -hhhd/`````.```osyyyyyyyyhhyyyyyy"<<"                                       sssyysssssyssss+``` `` ``` -hhhd/`````.```osyyyyyyyyhhyyyyyy"<<endl;
cout<<"yyyssyssssssssso.````````` yyhhdh````````.ssyyyyyyyyyyyyyyys"<<"                                       yyyssyssssssssso.````````` yyhhdh````````.ssyyyyyyyyyyyyyyys"<<endl;
cout<<"ssssssssssssssss/`````````.hhhhdd:```````:sssyyyysyyyyyyyyyy"<<"                                       ssssssssssssssss/`````````.hhhhdd:```````:sssyyyysyyyyyyyyyy"<<endl;
}

void manusiavsgajah()
{
cout<<"                            `.---.```"<<"                                                                                  `:+syyyyssso+:`"<<endl;
cout<<"                       ./shmmmmmmmmmmdys+-"<<"                                                                          :shs/-`       .:odh+`"<<endl;
cout<<"                    `+hdmNmmmmmmmmmNNNNNmmdo."<<"                                                          .:/+++/-`  /mh:                -ym/     .---.   "<<endl;
cout<<"                  -ommmmmmNNNmmmmmmmmmNNNNNmd/"<<"                                                       odms+/:::+syhNs     `-       .     +N:/ohdddmNNNh-"<<endl;
cout<<"               :ymmNmmmmNmmNmmmmmNNNNNNNNNNmmho-"<<"                                                     `om.        dd     /o`       +/.    hNs:`     `N/  "<<endl;
cout<<"               -dmmmNNmNNmmmmmmmmmmmmNNNNNNNNmddds."<<"                                                    mh        hs  `/+.                ss        /N"<<endl;
cout<<"               /mmmmmmNNmmmmmNmmmddmmNNNNNNNNmmmdmd-"<<"                                                   mm        om      `:+++++oos+`    m/        yN`"<<endl;
cout<<"              -mmNNmdyhdmNNNNmmdddmmmNNNNNmmmddddmmd:"<<"                                                 .Nd        oN     .:. `.-:::-.    -N:        oN:"<<endl;
cout<<"             `hmmmmds//+oyhddddhhhddddddddhhhyyydmNNm-"<<"                                                /Ns       .m/o`      --:::---:-   `N:        :Ns"<<endl;
cout<<"            .ymmmmdy+/::::::::::://+++++++//++oohmmNmo"<<"                                                sN:       sd dy      ://////:`   :/m:        .Ny"<<endl;
cout<<"            /dmNmmhs+/:::::-------------:::///++smmNms"<<"                                                hN`       :N/`h       `--:::     mdd         .No"<<endl;
cout<<"            -dmmmds+//::::---------------::///++odmNm:"<<"                                                sh         /myo         -//.     mNo         yh`       "<<endl;
cout<<"          ::-ddmdy+////::::---::--:::::::::///++sdmNd."<<"                                                -h         /mo          .:`      +Ny        sd`"<<endl;
cout<<"          //:+dmho//////:::-----:::::::::::///++odmmy"<<"                     .s: .smmmdy+```"<<"             h:       :N+                     :N+      ym."<<endl;
cout<<"          .::/hdo////+sss+/:-----:::--:::::/+oooohmdo"<<"        . :         `ydh+NNmo."<<"                   .d.   `/omN`.`       `//:`     `.`dhy+`  sm."<<endl;
cout<<"           -:/hh/://+ossyhhs+/::-::::::::+syhhhy+ydy/"<<"        -/:+.       -ddmMNm-"<<"                      -d:-hy/`+Nhmsy.             .ss/yN- /m+-N:"<<endl;
cout<<"           --:os/:://+ooyysyyys/:::://+oyyyysssy+yy/`"<<"        `os+s.      +dmNMNh"<<"                        .hN/    :mo :N/    `--.   `mN+ `N:  .ohs"<<endl;
cout<<"           -::////::/++/oo//oos+:::/ossoyys/osoo+h:"<<"           .syss-     ymmdMNN/"<<"                         `      m. :dN:     ``   :NhN- mo"<<endl;
cout<<"           .-:////::::::::://///:::/ooo/+o/:+o++++"<<"             :yhyy-   -mmm.oNNmdso/:."<<"                          N` d:sm`   -..`  +N+ys mo"<<endl;
cout<<"           `-::///:::------:::::::::++/::///+++++"<<"               :hddh-  ymmh  -sdmmmddhy/`"<<"                       d:-N``m+         oN/+h-N:"<<endl;
cout<<"             ``.///::-----::/:::::::+++/::::/+++/"<<"                /dmmd--mNN:     .-:+hdhhs."<<"                      /h/d  sh   -::-  +N:/hyd"<<endl;
cout<<"               `///:::-:://///:::---/+++/:::///-`"<<"                 /dmmddNNd           /hhhs"<<"                       +yh  +m  -//:`  yN-sNy."<<endl;
cout<<"              .:+//////+++//+oo+/:::+oo++//////"<<"                    :dNNNNN+           -hhhy"<<"                            sm  `+o+/ .NN`"<<endl;
cout<<"            `/yds+//+/+oso++//+oo++osssoo++/++:"<<"                     -dNNNm`          -yhhy:"<<"                           `ms   .:/. yN+"<<endl;
cout<<"          `:oyhy-/++//+o+ooo++/++ossssyyso++++`"<<"                      -dMMo   `  .`.-ohhhy/"<<"                           .hs   --.` +Ns"<<endl;
cout<<"       `:+oyys+-./o+++////++++++oossssso+++os-"<<"                        .dN`    .-sddddhy+."<<"                           +m/  ./:.` +Ns"<<endl;
cout<<"    `./ossssso-...+ooo+/////+++++oooooo++oshdyo:`"<<"                      `+      `-/++:-`"<<"                           .hd- .-  `` oNo"<<endl;
cout<<"`-:+sssssyyss/..```-++o+/////://///+++++osyddhyys+:`"<<"                                                             .hd- .-  `` oNo"<<endl;
cout<<"sssysssssssss:`.`````-:++++///////++++///soyhhhhyhhyo/.`"<<"                                                         .hd- .-  `` oNo"<<endl;
cout<<"ssyssysssysso:`````````.-/++ooooooo/::://++shhhhhyhhhhyso/-`"<<"                                                 `-:+Ny`   .:-``hm/ "<<endl;
cout<<"yyssssssyysss/````````````.:+sss+:--::://++shhhhhhhyhhhyyyyy"<<"                                                .d:+Ny   ::-  /my. "<<endl;
cout<<"yssssssssssss+`````     ````-+ss-..--::::/:syyhhhhyyyhhhhyyy"<<"                                               .y:+Nd`:`    :hh-"<<endl;
cout<<"ysssssssssssso.``         `-hddmd:...------syyyyyyyyyyyhhyyy"<<"                                               h- :N: `-- :hymo "<<endl;
cout<<"ssssssssssssss:`          `-ydddd/........-sssyyyyyyyyyyyyyy"<<"                                               s+/sN/-. `hmm.m+ "<<endl;
cout<<"ysssssssssssos+``        ...+mddo--.......:syyyyyyyyyyyyyyyy"<<"                                               s+/sN/-. `hmm.m+"<<endl;
cout<<"yhyssssssssssos-` ```   ````+dhd.```.``.../ssyyyyyyyyyhhhyys"<<"                                                `+mN:   -:.`sm` "<<endl;
cout<<"sssyysssssyssss+``` `` ``` -hhhd/`````.```osyyyyyyyyhhyyyyyy"<<"                                                  `yd:`  `/hh. "<<endl;
cout<<"yyyssyssssssssso.````````` yyhhdh````````.ssyyyyyyyyyyyyyyys"<<"                                                    /yyssys:"<<endl;
cout<<"ssssssssssssssss/`````````.hhhhdd:```````:sssyyyysyyyyyyyyyy"<<"                                                       ss"<<endl;
}

void gajahvssemut()
{
cout<<"                  `:+syyyyssso+:`"<<"                                                                               `-.                              .-`"<<endl;
cout<<"               :shs/-`       .:odh+`"<<"                                                                              `-`                          `-`"<<endl;
cout<<"  .:/+++/-`  /mh:                -ym/     .---."<<"                                                                     -.                        .-"<<endl;
cout<<"odms+/:::+syhNs     `-       .     +N:/ohdddmNNNh-"<<"                                                                   -.                      .-"<<endl;
cout<<"`om.        dd     /o`       +/.    hNs:`     `N/"<<"                                                                     :.                    .:"<<endl;
cout<<"  mh        hs  `/+.                ss        /N"<<"                                                                       :.                  .:"<<endl;
cout<<"  mm        om      `:+++++oos+`    m/        yN`"<<"                                                                       ::`              `::"<<endl;
cout<<" .Nd        oN     .:. `.-:::-.    -N:        oN:"<<"                                                                        `::-` `-`.-` `-::`"<<endl;
cout<<" /Ns       .m/o`      --:::---:-   `N:        :Ns"<<"                                                              .              `:/hy//yy/:`              ."<<endl;
cout<<" sN:       sd dy      ://////:`   :/m:        .Ny"<<"                                                              .-`             .yhhdddhy.             `-."<<endl;
cout<<"hN`       :N/`h       `--:::     mdd         .No"<<"                                                                 ..``         .hhhhhhhhhy`         `..."<<endl;
cout<<"sh         /myo         -//.     mNo         yh`"<<"                                                                    .-        yhhhhhhhhhhs        -."<<endl;
cout<<" -h         /mo          .:`      +Ny        sd`"<<"                                                                      :.     `hyoooyyhhyyh      .:"<<endl;
cout<<"  h:       :N+                     :N+      ym."<<"                             -    `-+++/:-`"<<"                             /-     shhhhhhhhhho     -/"<<endl;
cout<<"  .d.   `/omN`.`       `//:`     `.`dhy+`  sm."<<"                             .s: .smmmdy+```"<<"                              +-     `./hddh/.`     -+"<<endl;
cout<<"   -d:-hy/`+Nhmsy.             .ss/yN- /m+-N:"<<"                 . :         `ydh+NNmo."<<"                                     +.     shyyhhho     .+"<<endl;
cout<<"    .hN/    :mo :N/    `--.   `mN+ `N:  .ohs"<<"                  -/:+.       -ddmMNm-"<<"                                        ++`   yhhhhhhs   `++"<<endl;
cout<<"      `      m. :dN:     ``   :NhN- mo"<<"                        `os+s.      +dmNMNh"<<"                                          -s+` -ddhddd- `+s-"<<endl;
cout<<"             N` d:sm`   -..`  +N+ys mo"<<"                         .syss-     ymmdMNN/"<<"                                           :o+ohhhhhho+o:"<<endl;
cout<<"             d:-N``m+         oN/+h-N:"<<"                          :yhyy-   -mmm.oNNmdso/:."<<"                                         shyhho"<<endl;
cout<<"             /h/d  sh   -::-  +N:/hyd"<<"                            :hddh-  ymmh  -sdmmmddhy/`"<<"                       `-...--...`   `dddddh    `...--...-`"<<endl;
cout<<"              +yh  +m  -//:`  yN-sNy."<<"                             /dmmd--mNN:     .-:+hdhhs."<<"                  `-::----://++o++//sdyyhhds//++o++//:----::-`"<<endl;
cout<<"                   sm  `+o+/ .NN`"<<"                                  /dmmddNNd           /hhhs"<<"               `:::`                -hhhhhh-                .:::`"<<endl;
cout<<"                  `ms   .:/. yN+"<<"                                    :dNNNNN+           -hhhy"<<"            `....                `-oy+ohh++yo-`                ....`"<<endl;
cout<<"                 .hs   --.` +Ns"<<"                                      -dNNNm`          -yhhy:"<<"        ```...`            .:///:-.   -hh.   .-:///:.            `...```"<<endl;
cout<<"                +m/  ./:.` +Ns"<<"                                        -dMMo   `  .`.-ohhhy/"<<"          ````           -+s/-`      -sdhdds.      `-/s+-           ````"<<endl;
cout<<"              .hd- .-  `` oNo"<<"                                          .dN`    .-sddddhy+."<<"                       .+o/.        `ohhdhddhh+         ./o+."<<endl;
cout<<"          `-:+Ny`   .:-``hm/"<<"                                            `+      `-/++:-`"<<"                      -//:`           sdhhhddhhhdo           `://-"<<endl;
cout<<"         .d:+Ny   ::-  /my."<<"                                                                                   ::`            :dddhshdddddd.             `::"<<endl;
cout<<"        .y:+Nd`:`    :hh-"<<"                                                                                   `/               +dhhdddddddhd:               /`"<<endl;
cout<<"        h- :N: `-- :hymo"<<"                                                                                    -/               :dhhhhddhhhhd-               /-"<<endl;
cout<<"        s+/sN/-. `hmm.m+"<<"                                                                                    /-                sddhhhhhdddo                -/"<<endl;
cout<<"         `+mN:   -:.`sm`"<<"                                                                                    /-                 /hdhddddh:                 -/"<<endl;
cout<<"           `yd:`  `/hh."<<"                                                                                     :                    -/++/.                    :"<<endl;
cout<<"             /yyssys:"<<"                                                                                       `-                                              -`"<<endl;
}

void gajahvsmanusia()
{
cout<<"                  `:+syyyyssso+:`"<<"                                                                                              `.---.```"<<endl;
cout<<"               :shs/-`       .:odh+`"<<"                                                                                      ./shmmmmmmmmmmdys+-"<<endl;
cout<<"  .:/+++/-`  /mh:                -ym/     .---."<<"                                                                        `+hdmNmmmmmmmmmNNNNNmmdo."<<endl;
cout<<"odms+/:::+syhNs     `-       .     +N:/ohdddmNNNh-"<<"                                                                   -ommmmmmNNNmmmmmmmmmNNNNNmd/"<<endl;
cout<<"`om.        dd     /o`       +/.    hNs:`     `N/"<<"                                                                  :ymmNmmmmNmmNmmmmmNNNNNNNNNNmmho-"<<endl;
cout<<"  mh        hs  `/+.                ss        /N"<<"                                                                   -dmmmNNmNNmmmmmmmmmmmmNNNNNNNNmddds."<<endl;
cout<<"  mm        om      `:+++++oos+`    m/        yN`"<<"                                                                  /mmmmmmNNmmmmmNmmmddmmNNNNNNNNmmmdmd-"<<endl;
cout<<" .Nd        oN     .:. `.-:::-.    -N:        oN:"<<"                                                                 -mmNNmdyhdmNNNNmmdddmmmNNNNNmmmddddmmd:"<<endl;endl;
cout<<" /Ns       .m/o`      --:::---:-   `N:        :Ns"<<"                                                                `hmmmmds//+oyhddddhhhddddddddhhhyyydmNNm-"<<endl;
cout<<" sN:       sd dy      ://////:`   :/m:        .Ny"<<"                                                               .ymmmmdy+/::::::::::://+++++++//++oohmmNmo"<<endl;endl;
cout<<"hN`       :N/`h       `--:::     mdd         .No"<<"                                                                /dmNmmhs+/:::::-------------:::///++smmNms"<<endl;
cout<<"sh         /myo         -//.     mNo         yh`"<<"                                                                -dmmmds+//::::---------------::///++odmNm:"<<endl;
cout<<" -h         /mo          .:`      +Ny        sd`"<<"                                                                ::-ddmdy+////::::---::--:::::::::///++sdmNd."<<endl;endl;
cout<<"  h:       :N+                     :N+      ym."<<"                             -    `-+++/:-`"<<"                      //:+dmho//////:::-----:::::::::::///++odmmy"<<endl;
cout<<"  .d.   `/omN`.`       `//:`     `.`dhy+`  sm."<<"                             .s: .smmmdy+```"<<"                      .::/hdo////+sss+/:-----:::--:::::/+oooohmdo"<<endl;
cout<<"   -d:-hy/`+Nhmsy.             .ss/yN- /m+-N:"<<"                 . :         `ydh+NNmo."<<"                             -:/hh/://+ossyhhs+/::-::::::::+syhhhy+ydy/"<<endl;
cout<<"    .hN/    :mo :N/    `--.   `mN+ `N:  .ohs"<<"                  -/:+.       -ddmMNm-"<<"                               --:os/:://+ooyysyyys/:::://+oyyyysssy+yy/`"<<endl;
cout<<"      `      m. :dN:     ``   :NhN- mo"<<"                        `os+s.      +dmNMNh"<<"                                -::////::/++/oo//oos+:::/ossoyys/osoo+h:"<<endl;
cout<<"             N` d:sm`   -..`  +N+ys mo"<<"                         .syss-     ymmdMNN/"<<"                               .-:////::::::::://///:::/ooo/+o/:+o++++"<<endl;
cout<<"             d:-N``m+         oN/+h-N:"<<"                          :yhyy-   -mmm.oNNmdso/:."<<"                         `-::///:::------:::::::::++/::///+++++"<<endl;
cout<<"             /h/d  sh   -::-  +N:/hyd"<<"                            :hddh-  ymmh  -sdmmmddhy/`"<<"                        ``.///::-----::/:::::::+++/::::/+++/"<<endl;
cout<<"              +yh  +m  -//:`  yN-sNy."<<"                             /dmmd--mNN:     .-:+hdhhs."<<"                         `///:::-:://///:::---/+++/:::///-`"<<endl;
cout<<"                   sm  `+o+/ .NN`"<<"                                  /dmmddNNd           /hhhs"<<"                        .:+//////+++//+oo+/:::+oo++//////"<<endl;
cout<<"                  `ms   .:/. yN+"<<"                                    :dNNNNN+           -hhhy"<<"                      `/yds+//+/+oso++//+oo++osssoo++/++:"<<endl;
cout<<"                 .hs   --.` +Ns"<<"                                      -dNNNm`          -yhhy:"<<"                    `:oyhy-/++//+o+ooo++/++ossssyyso++++`"<<endl;
cout<<"                +m/  ./:.` +Ns"<<"                                        -dMMo   `  .`.-ohhhy/"<<"                  `:+oyys+-./o+++////++++++oossssso+++os-"<<endl;
cout<<"              .hd- .-  `` oNo"<<"                                          .dN`    .-sddddhy+."<<"                `./ossssso-...+ooo+/////+++++oooooo++oshdyo:`"<<endl;
cout<<"          `-:+Ny`   .:-``hm/"<<"                                            `+      `-/++:-`"<<"              `-:+sssssyyss/..```-++o+/////://///+++++osyddhyys+:`"<<endl;
cout<<"         .d:+Ny   ::-  /my."<<"                                                                           sssysssssssss:`.`````-:++++///////++++///soyhhhhyhhyo/.`"<<endl;
cout<<"        .y:+Nd`:`    :hh-"<<"                                                                             ssyssysssysso:`````````.-/++ooooooo/::://++shhhhhyhhhhyso/-`"<<endl;
cout<<"        h- :N: `-- :hymo"<<"                                                                              yyssssssyysss/````````````.:+sss+:--::://++shhhhhhhyhhhyyyyy"<<endl;
cout<<"        s+/sN/-. `hmm.m+"<<"                                                                              yssssssssssss+`````     ````-+ss-..--::::/:syyhhhhyyyhhhhyyy"<<endl;
cout<<"         `+mN:   -:.`sm`"<<"                                                                              ysssssssssssso.``         `-hddmd:...------syyyyyyyyyyyhhyyy"<<endl;
cout<<"           `yd:`  `/hh."<<"                                                                               ssssssssssssss:`          `-ydddd/........-sssyyyyyyyyyyyyyy"<<endl;
cout<<"             /yyssys:"<<"                                                                                 ysssssssssssos+``        ...+mddo--.......:syyyyyyyyyyyyyyyy"<<endl;
}

void gajahvsgajah()
{
cout<<"                  `:+syyyyssso+:`"<<"                                                                                        `:+syyyyssso+:`"<<endl;
cout<<"               :shs/-`       .:odh+`"<<"                                                                                  :shs/-`       .:odh+`"<<endl;
cout<<"  .:/+++/-`  /mh:                -ym/     .---."<<"                                                          .:/+++/-`  /mh:                -ym/     .---."<<endl;
cout<<"odms+/:::+syhNs     `-       .     +N:/ohdddmNNNh-"<<"                                                     odms+/:::+syhNs     `-       .     +N:/ohdddmNNNh-"<<endl;
cout<<"`om.        dd     /o`       +/.    hNs:`     `N/"<<"                                                      `om.        dd     /o`       +/.    hNs:`     `N/"<<endl;
cout<<"  mh        hs  `/+.                ss        /N"<<"                                                         mh        hs  `/+.                ss        /N"<<endl;
cout<<"  mm        om      `:+++++oos+`    m/        yN`"<<"                                                        mm        om      `:+++++oos+`    m/        yN`"<<endl;
cout<<" .Nd        oN     .:. `.-:::-.    -N:        oN:"<<"                                                       .Nd        oN     .:. `.-:::-.    -N:        oN:"<<endl;
cout<<" /Ns       .m/o`      --:::---:-   `N:        :Ns"<<"                                                       /Ns       .m/o`      --:::---:-   `N:        :Ns"<<endl;
cout<<" sN:       sd dy      ://////:`   :/m:        .Ny"<<"                                                       sN:       sd dy      ://////:`   :/m:        .Ny"<<endl;
cout<<"hN`       :N/`h       `--:::     mdd         .No"<<"                                                       hN`       :N/`h       `--:::     mdd         .No"<<endl;
cout<<"sh         /myo         -//.     mNo         yh`"<<"                                                       sh         /myo         -//.     mNo         yh`"<<endl;
cout<<" -h         /mo          .:`      +Ny        sd`"<<"                                                        -h         /mo          .:`      +Ny        sd`"<<endl;
cout<<"  h:       :N+                     :N+      ym."<<"                             -    `-+++/:-`"<<"               h:       :N+                     :N+      ym."<<endl;
cout<<"  .d.   `/omN`.`       `//:`     `.`dhy+`  sm."<<"                             .s: .smmmdy+```"<<"               .d.   `/omN`.`       `//:`     `.`dhy+`  sm."<<endl;
cout<<"   -d:-hy/`+Nhmsy.             .ss/yN- /m+-N:"<<"                 . :         `ydh+NNmo."<<"                      -d:-hy/`+Nhmsy.             .ss/yN- /m+-N:"<<endl;
cout<<"    .hN/    :mo :N/    `--.   `mN+ `N:  .ohs"<<"                  -/:+.       -ddmMNm-"<<"                         .hN/    :mo :N/    `--.   `mN+ `N:  .ohs"<<endl;
cout<<"      `      m. :dN:     ``   :NhN- mo"<<"                        `os+s.      +dmNMNh"<<"                                   m. :dN:     ``   :NhN- mo"<<endl;
cout<<"             N` d:sm`   -..`  +N+ys mo"<<"                         .syss-     ymmdMNN/"<<"                                  N` d:sm`   -..`  +N+ys mo"<<endl;
cout<<"             d:-N``m+         oN/+h-N:"<<"                          :yhyy-   -mmm.oNNmdso/:."<<"                            d:-N``m+         oN/+h-N:"<<endl;
cout<<"             /h/d  sh   -::-  +N:/hyd"<<"                            :hddh-  ymmh  -sdmmmddhy/`"<<"                         /h/d  sh   -::-  +N:/hyd"<<endl;
cout<<"              +yh  +m  -//:`  yN-sNy."<<"                             /dmmd--mNN:     .-:+hdhhs."<<"                         +yh  +m  -//:`  yN-sNy."<<endl;
cout<<"                   sm  `+o+/ .NN`"<<"                                  /dmmddNNd           /hhhs"<<"                              sm  `+o+/ .NN`"<<endl;
cout<<"                  `ms   .:/. yN+"<<"                                    :dNNNNN+           -hhhy"<<"                             `ms   .:/. yN+"<<endl;
cout<<"                 .hs   --.` +Ns"<<"                                      -dNNNm`          -yhhy:"<<"                            .hs   --.` +Ns"<<endl;
cout<<"                +m/  ./:.` +Ns"<<"                                        -dMMo   `  .`.-ohhhy/"<<"                            +m/  ./:.` +Ns"<<endl;
cout<<"              .hd- .-  `` oNo"<<"                                          .dN`    .-sddddhy+."<<"                           .hd- .-  `` oNo"<<endl;
cout<<"          `-:+Ny`   .:-``hm/"<<"                                            `+      `-/++:-`"<<"                         `-:+Ny`   .:-``hm/"<<endl;
cout<<"         .d:+Ny   ::-  /my."<<"                                                                                     .d:+Ny   ::-  /my."<<endl;
cout<<"        .y:+Nd`:`    :hh-"<<"                                                                                      .y:+Nd`:`    :hh-"<<endl;
cout<<"        h- :N: `-- :hymo"<<"                                                                                       h- :N: `-- :hymo"<<endl;
cout<<"        s+/sN/-. `hmm.m+"<<"                                                                                       s+/sN/-. `hmm.m+"<<endl;
cout<<"         `+mN:   -:.`sm`"<<"                                                                                        `+mN:   -:.`sm`"<<endl;
cout<<"           `yd:`  `/hh."<<"                                                                                           `yd:`  `/hh."<<endl;
cout<<"             /yyssys:"<<"                                                                                               /yyssys:"<<endl;
}

void cover()
{
int option1,option2;
cout<<"                                                                                                                                                                       "<<endl;
cout<<"                                                                                                                                                                       "<<endl;
cout<<"                                                                                                                                                                       "<<endl;
cout<<"                                                                                                                                                                       "<<endl;
cout<<"                                                                                                                                                                       "<<endl;
cout<<"                                                                                                                                                                       "<<endl;
cout<<"                                                                                                                                                                       "<<endl;
cout<<"                                                                                                                                                                       "<<endl;
cout<<"                                                                                                                                                                       "<<endl;
cout<<"                                                                              --:::////:::--                                                                           "<<endl;
cout<<"                                                                         -:///++++++++++++++///:-                                                                      "<<endl;
cout<<"                                                                      -//++++++++++++++++++++++++/:-                                                                   "<<endl;
cout<<"                                                                    :/++++++++++++++++++++++++++++++/:                                                                 "<<endl;
cout<<"                                                                  :/++++++++++++++++++++++++++++++++++/:                                                               "<<endl;
cout<<"                                                                -/++++++++++++++++++++++++++++++++++++++/-                                                             "<<endl;
cout<<"                                                               :++++++++++++++++++++++++++++++++++++++++++:                                                            "<<endl;
cout<<"                                                              :++++++++++++ss++++++++++++++++ss++++++++++++:                                                           "<<endl;
cout<<"                                                             -+++++++++++++sy++ssssssssssssssys+++++++++++++-                                                          "<<endl;
cout<<"                                                            ./++++++++++++++ys+oooooooooooosyy++++++++++++++/.       -/:::             -o- -:         -:               "<<endl;
cout<<"                ://:                          -/  .-        :++++++++++++++++sys++oooooooosys++++++++++++++++:       +y  os            -y:            +y               "<<endl;
cout<<"              -s+--+s-                    ++/     /y        /+++++++++++++++++osysooooosyyso+++++++++++++++++/       +y  os  +++s+  /s++y: /y  +++s+. +s               "<<endl;
cout<<"              os    so :s++s: +s/+y+/os  so/  :y  oy+-      /++++++++++++++++++++osysoooo++++++++++++++++++++/       +y+oy:   /+oy  y/  y: /y   ++oy- +o               "<<endl;
cout<<"              os    so os//so +s  y+  y  oo.  :y  /y        /++++++++++++++++++++osyssyso++++++++++++++++++++/       +y  os  y/ /y  y/  y: /y  y/./y-                  "<<endl;
cout<<"              /y    y/ os     +s  y+  y   -os :y  /y        /+++++++++++++++++osysooooosyyso+++++++++++++++++/.      +s  -s  oo++s  /s++s: /y  oo++s- oo               "<<endl;
cout<<"               /o++o/  -+o++: /o  s/  s  o+o/ :s  -o+-      :++++++++++++++++sys++oooooooosys++++++++++++++++:                             +y                          "<<endl;
cout<<"                                                            ./++++++++++++++ys+oooooooooooosyy++++++++++++++/.                            //:                          "<<endl;
cout<<"                                                             -+++++++++++++sy++ssssssssssssssys+++++++++++++-                                                          "<<endl;
cout<<"                                                              :++++++++++++ss++++++++++++++++ss++++++++++++:                                                           "<<endl;
cout<<"                                                               :++++++++++++++++++++++++++++++++++++++++++:                                                            "<<endl;
cout<<"                                                                 -/++++++++++++++++++++++++++++++++++++++/-                                                            "<<endl;
cout<<"                                                                  :/++++++++++++++++++++++++++++++++++/:                                                               "<<endl;
cout<<"                                                                    :/++++++++++++++++++++++++++++++/:                                                                 "<<endl;
cout<<"                                                                      -:/++++++++++++++++++++++++//-                                                                   "<<endl;
cout<<"                                                                         -:///++++++++++++++///:-                                                                      "<<endl;
cout<<"                                                                              --:::://::::--                                                                           "<<endl;
cout<<"                                                                                                                                                                       "<<endl;
cout<<"                                                                                1 Play                                                                                "<<endl;
cout<<"                                                                                2 Scoreboard                                                                          "<<endl;
cout<<"                                                                                3 Exit                                                                                 "<<endl;
cout<<"                                                                           Masukkan Pilihan Anda:";
cin>>option1;
switch(option1)
{
case 1: system("cls");
			cout<<"                                                                                                                                                                       "<<endl;
			cout<<"                                                                                                                                                                       "<<endl;
			cout<<"                                                                                                                                                                       "<<endl;
			cout<<"                                                                                                                                                                       "<<endl;
			cout<<"                                                                                                                                                                       "<<endl;
			cout<<"                                                                                                                                                                       "<<endl;
			cout<<"                                                                                                                                                                       "<<endl;
			cout<<"                                                                                                                                                                       "<<endl;
			cout<<"                                                                                                                                                                       "<<endl;
			cout<<"                                                                              --:::////:::--                                                                           "<<endl;
			cout<<"                                                                         -:///++++++++++++++///:-                                                                      "<<endl;
			cout<<"                                                                      -//++++++++++++++++++++++++/:-                                                                   "<<endl;
			cout<<"                                                                    :/++++++++++++++++++++++++++++++/:                                                                 "<<endl;
			cout<<"                                                                  :/++++++++++++++++++++++++++++++++++/:                                                               "<<endl;
			cout<<"                                                                -/++++++++++++++++++++++++++++++++++++++/-                                                             "<<endl;
			cout<<"                                                               :++++++++++++++++++++++++++++++++++++++++++:                                                            "<<endl;
			cout<<"                                                              :++++++++++++ss++++++++++++++++ss++++++++++++:                                                           "<<endl;
			cout<<"                                                             -+++++++++++++sy++ssssssssssssssys+++++++++++++-                                                          "<<endl;
			cout<<"                                                            ./++++++++++++++ys+oooooooooooosyy++++++++++++++/.       -/:::             -o- -:         -:               "<<endl;
			cout<<"                ://:                          -/  .-        :++++++++++++++++sys++oooooooosys++++++++++++++++:       +y  os            -y:            +y               "<<endl;
			cout<<"              -s+--+s-                    ++/     /y        /+++++++++++++++++osysooooosyyso+++++++++++++++++/       +y  os  +++s+  /s++y: /y  +++s+. +s               "<<endl;
			cout<<"              os    so :s++s: +s/+y+/os  so/  :y  oy+-      /++++++++++++++++++++osysoooo++++++++++++++++++++/       +y+oy:   /+oy  y/  y: /y   ++oy- +o               "<<endl;
			cout<<"              os    so os//so +s  y+  y  oo.  :y  /y        /++++++++++++++++++++osyssyso++++++++++++++++++++/       +y  os  y/ /y  y/  y: /y  y/./y-                  "<<endl;
			cout<<"              /y    y/ os     +s  y+  y   -os :y  /y        /+++++++++++++++++osysooooosyyso+++++++++++++++++/.      +s  -s  oo++s  /s++s: /y  oo++s- oo               "<<endl;
			cout<<"               /o++o/  -+o++: /o  s/  s  o+o/ :s  -o+-      :++++++++++++++++sys++oooooooosys++++++++++++++++:                             +y                          "<<endl;
			cout<<"                                                            ./++++++++++++++ys+oooooooooooosyy++++++++++++++/.                            //:                          "<<endl;
			cout<<"                                                             -+++++++++++++sy++ssssssssssssssys+++++++++++++-                                                          "<<endl;
			cout<<"                                                              :++++++++++++ss++++++++++++++++ss++++++++++++:                                                           "<<endl;
			cout<<"                                                               :++++++++++++++++++++++++++++++++++++++++++:                                                            "<<endl;
			cout<<"                                                                 -/++++++++++++++++++++++++++++++++++++++/-                                                            "<<endl;
			cout<<"                                                                  :/++++++++++++++++++++++++++++++++++/:                                                               "<<endl;
			cout<<"                                                                    :/++++++++++++++++++++++++++++++/:                                                                 "<<endl;
			cout<<"                                                                      -:/++++++++++++++++++++++++//-                                                                   "<<endl;
			cout<<"                                                                         -:///++++++++++++++///:-                                                                      "<<endl;
			cout<<"                                                                              --:::://::::--                                                                           "<<endl;
		   cout<<"                                                                            1 Player Vs CPU"<<endl;
		  	cout<<"                                                                            2 Player Vs Player"<<endl;
        	cout<<"                                                                            3 Survival Mode"<<endl;
         cout<<"                                                                            4 Return to Main Menu"<<endl;
        	cout<<"                                                                            Masukkan Pilihan Anda:";
        	cin>>option2;
        	switch(option2)
        	{
        	case 1 : {system("cls");
         			cout<<"Cara bermain"<<endl;
         			cout<<"- Pilih pilihan suit yang Anda inginkan."<<endl;
                  cout<<"- 1 untuk memilih semut."<<endl;
                  cout<<"- 2 untuk memilih manusia."<<endl;
                  cout<<"- 3 untuk memilih gajah."<<endl;
                  cout<<"- Semut menang melawan gajah, tetapi kalah melawan manusia."<<endl;
                  cout<<"- Manusia menang melawan semut, tetapi kalah melawan gajah."<<endl;
                  cout<<"- Gajah menang melawan manusia, tetapi kalah melawan semut."<<endl;
                  cout<<"- Apabila player/CPU memenangi suit, maka player/CPU mendapat +10 point."<<endl;
                  cout<<"- Player/CPU yang mencapai poin 50 akan menjadi pemenang."<<endl;
         			int CPUnum,b,CPUscore=0,Humanscore=0;
						string Komputer,Human,nama;
						cout<<"Masukkan Nama Anda:";
						getline(cin,nama);
						do
						{
   						cout<<"Suit:";
  	 						cin>>b;
   						randomize();
   						CPUnum = random(3);
   						if (b == 1)
    								Human = "Semut";
      							else
   									if (b == 2)
    									Human = "Manusia";
      								else
   										if (b == 3)
      									Human = "Gajah";
   						if (CPUnum == 0)
    								Komputer = "Semut";
      							else
   									if (CPUnum == 1)
    									Komputer = "Manusia";
      								else
   										if (CPUnum == 2)
               						Komputer = "Gajah";
							cout<<Human<<"\t\t\t\t"<<"VS"<<"\t\t\t"<<Komputer<<endl;

   						if		(b == 1 && CPUnum == 0)
   								{  system("cls");
            						semutvssemut();
           						 	cout << "Ant meets another Ant, its a tie!" << endl;
                              Humanscore += 0;
            						CPUscore += 0;
            						cout <<nama<<"'s"<<" score: "<<Humanscore<<endl;
            						cout <<"CPU's score: "<<CPUscore<<endl;
         						}
    								else
   						if		(b == 1 && CPUnum == 1)
   							  	{  system("cls");
            						semutvsmanusia();
         							cout << "Ant is stepped on by Human, CPU wins!" << endl;
            						Humanscore += 0;
            						CPUscore += 10;
            						cout <<nama<<"'s"<<" score: "<<Humanscore<<endl;
            						cout <<"CPU's score: "<<CPUscore<<endl;

         						}
   								 else
   						if		(b == 1 && CPUnum == 2)
   								{  system("cls");
            						semutvsgajah();
         							cout << "Ant goes into elephant's ear!, "<<nama<<" wins!" << endl;
            						Humanscore += 10;
            						CPUscore += 0;
                              cout <<nama<<"'s"<<" score: "<<Humanscore<<endl;
            						cout <<"CPU's score: "<<CPUscore<<endl;

         						}
                            else
   						if		(b == 2 && CPUnum == 0)
   								{  system("cls");
                           	manusiavssemut();
         							cout << "Ant is stepped on by Human, "<<nama<<" wins!" << endl;
            						Humanscore += 10;
                              CPUscore += 0;
            						cout <<nama<<"'s"<<" score: "<<Humanscore<<endl;
            						cout <<"CPU's score: "<<CPUscore<<endl;
         						}
    								else
   						if		(b == 2 && CPUnum == 1)
   								{  system("cls");
            						manusiavsmanusia();
         						  	cout << "Human meets Human, its a tie!" << endl;
                              Humanscore += 0;
            						CPUscore += 0;
            						cout <<nama<<"'s"<<" score: "<<Humanscore<<endl;
            						cout <<"CPU's score: "<<CPUscore<<endl;
         						}
    								else
   						if		(b == 2 && CPUnum == 2)
    								{  system("cls");
         							manusiavsgajah();
         							cout << "Human is stepped on by elephant, CPU wins!" << endl;
            						Humanscore += 0;
            						CPUscore += 10;
            						cout <<nama<<"'s"<<" score: "<<Humanscore<<endl;
            						cout <<"CPU's score: "<<CPUscore<<endl;

         						}
    								else
   						if		(b == 3 && CPUnum == 0)
   								{	system("cls");
                           	gajahvssemut();
         							cout << "Ant goes into elephant's ear! CPU wins!" << endl;
                              Humanscore += 0;
            						CPUscore += 10;
            						cout <<nama<<"'s"<<" score: "<<Humanscore<<endl;
            						cout <<"CPU's score: "<<CPUscore<<endl;

         						}
                           else
         				if		(b == 3 && CPUnum == 1)
   							  	{  system("cls");
         							gajahvsmanusia();
         							cout << "Human is stepped on by elephant, "<<nama<<" wins!" << endl;
         							Humanscore += 10;
            						CPUscore += 0;
            						cout <<nama<<"'s"<<" score: "<<Humanscore<<endl;
            						cout <<"CPU's score: "<<CPUscore<<endl;
         						}
    								else
   						if		(b == 3 && CPUnum == 2)
   								{	system("cls");
            						gajahvsgajah();
         							cout << "Elephant meets elephant, its a tie!" << endl;
         							Humanscore += 0;
            						CPUscore +=0;
            						cout <<nama<<"'s"<<" score: "<<Humanscore<<endl;
            						cout <<"CPU's score: "<<CPUscore<<endl;
         						}
   						if		(CPUscore == 50)
									{
         							system("cls");
                              cout<<"\t\t\t\t\t\t\t\t\tYou Lose, Try again next time!"<<endl;
                              lose();
                              cout<<"\t\t\t\t\t\t\t\t   Press any keys to return to Main Menu";
                              getch();
                              system("cls");
                              cover();
									}
   									else
							if		(Humanscore == 50)
								  	{
         							system("cls");
            						win();
                              cout<<"\t\t\t\t\t\t\t\t   Press any keys to return to Main Menu";
                              getch();
                              system("cls");
                              cover();
                           }
                  }
						while (CPUscore != 50 && Humanscore !=50);
						getch();break;}
         case 2 : system("cls");
         			cout<<"Cara bermain"<<endl;
         			cout<<"- Pilih pilihan suit yang Anda inginkan."<<endl;
                  cout<<"- 1 untuk memilih semut."<<endl;
                  cout<<"- 2 untuk memilih manusia."<<endl;
                  cout<<"- 3 untuk memilih gajah."<<endl;
                  cout<<" Semut menang melawan gajah, tetapi kalah melawan manusia."<<endl;
                  cout<<" Manusia menang melawan semut, tetapi kalah melawan gajah."<<endl;
                  cout<<" Gajah menang melawan manusia, tetapi kalah melawan semut."<<endl;
                  cout<<" Apabila player memenangi suit, maka player mendapat +1 point."<<endl;
                  cout<<" Player yang mencapai poin tertentu akan menjadi pemenang."<<endl;
                  {
						int Player1score=0,Player2score=0,a,b,c;
						string nama1,nama2,Human1,Human2;
						cout<<" Masukkan Nama Player1:";
						getline(cin,nama1);
						cout<<" Masukkan Nama Player2:";
						getline(cin,nama2);
						cout<<" Masukkan target poin:";
						cin>>c;
						do
						{
   					cout<<"Suit"<<nama1<<":";
   					cin>>a;
   					system("cls");
   					cout<<"Suit"<<nama2<<":";
   					cin>>b;
   					system("cls");
   					if (a == 1)
                  Human1 = "Semut";
      						else
   								if (a == 2)
    								Human1 = "Manusia";
      									else
   											if (a == 3)
      											Human1 = "Gajah";
  						 if ( b== 1)
                   Human2 = "Semut";
      						else
   								if (b == 2)
    								Human2 = "Manusia";
      									else
   											if (b == 3)
               								Human2 = "Gajah";
						cout<<Human1<<"\t\t\t\t"<<"VS"<<"\t\t\t"<<Human2<<endl;

   					if		(a == 1 && b == 1)
   					{  system("cls");
                  	semutvssemut();
                     cout << "Ant meets another Ant, its a tie!" << endl;
                     Player1score += 0;
                     Player2score += 0;
            			cout <<nama1<<"'s"<<" score: "<<Player1score<<endl;
            			cout <<nama2<<"'s"<<" score: "<<Player2score<<endl;
            			cout<<"Press Any Keys to Continue..."<<endl;
            			getch();
         			}
    					else
   					if		(a == 1 && b== 2)
   					{  system("cls");
           			 	semutvsmanusia();
                   	cout << "Ant is stepped on by Human, "<<nama2<<" wins!" << endl;
            			Player1score += 0;
            			Player2score += 1;
            			cout <<nama1<<"'s"<<" score: "<<Player1score<<endl;
            			cout <<nama2<<"'s"<<" score: "<<Player2score<<endl;
            			cout<<"Press Any Keys to Continue..."<<endl;;
            			getch();
         			}
    					else
   					if		(a == 1 && b == 3)
   					{  system("cls");
                  	semutvsgajah();
         				cout << "Ant goes into elephant's ear!, "<<nama1<<" wins!" << endl;
            			Player1score += 1;
            			Player2score += 0;
            			cout <<nama1<<"'s"<<" score: "<<Player1score<<endl;
            			cout <<nama2<<"'s"<<" score: "<<Player2score<<endl;
            			cout<<"Press Any Keys to Continue..."<<endl;;
            			getch();
         			}
    					else
  						 if		(a == 2 && b == 1)
   					{  system("cls");
							manusiavssemut();
         				cout << "Human steps on ant, "<<nama1<<" wins!" << endl;
            			Player1score += 1;
            			Player2score += 0;
            			cout <<nama1<<"'s"<<" score: "<<Player1score<<endl;
            			cout <<nama2<<"'s"<<" score: "<<Player2score<<endl;
            			cout<<"Press Any Keys to Continue..."<<endl;
            			getch();
                  }
    					else
   					if		(a == 2 && b == 2)
   					{  system("cls");
            			manusiavsmanusia();
         				cout << "Human meets Human, its a tie!" << endl;
         				Player1score += 0;
            			Player2score += 0;
            			cout <<nama1<<"'s"<<" score: "<<Player1score<<endl;
            			cout <<nama2<<"'s"<<" score: "<<Player2score<<endl;
                     cout<<"Press Any Keys to Continue..."<<endl;
            			getch();
         			}
    					else
   					if		(a == 2 && b == 3)
    					{  system("cls");
         				manusiavsgajah();
         				cout << "Human is stepped on by elephant, "<<nama2<<" wins!" << endl;
            			Player1score += 0;
            			Player2score += 1;
            			cout <<nama1<<"'s"<<" score: "<<Player1score<<endl;
            			cout <<nama2<<"'s"<<" score: "<<Player2score<<endl;
            			cout<<"Press Any Keys to Continue..."<<endl;
            			getch();
						}
    					else
   					if		(a == 3 && b == 1)
   					{	system("cls");
            			gajahvssemut();
         				cout << "Ant goes into elephant's ear!"<<nama2<<" wins!" << endl;
         				Player1score += 0;
            			Player2score += 1;
            			cout <<nama1<<"'s"<<" score: "<<Player1score<<endl;
            			cout <<nama2<<"'s"<<" score: "<<Player2score<<endl;
            			cout<<"Press Any Keys to Continue..."<<endl;
            			getch();
						}
    					else
   					if		(a == 3 && b == 2)
   					{  system("cls");
                  	gajahvsmanusia();
         				cout << "Elephant steps on human, "<<nama1<<" wins!" << endl;
         				Player1score += 1;
            			Player2score += 0;
            			cout <<nama1<<"'s"<<" score: "<<Player1score<<endl;
            			cout <<nama2<<"'s"<<" score: "<<Player2score<<endl;
            			cout<<"Press Any Keys to Continue..."<<endl;
            			getch();
         			}
    					else
   					if		(a == 3 && b == 3)
                  {	system("cls");
            			gajahvsgajah();
         				cout << "Elephant meets elephant, its a tie!" << endl;
         				Player1score += 0;
            			Player2score +=0;
            			cout <<nama1<<"'s"<<" score: "<<Player1score<<endl;
            			cout <<nama2<<"'s"<<" score: "<<Player2score<<endl;
            			cout<<"Press Any Keys to Continue..."<<endl;
            			getch();
         			}
   					if		(Player1score == c)
					  	{
         				system("cls");
							cout<<"\t\t\t\t\t\t\t\t\t     Congratulations " <<nama1<<"!"<<endl;
            			win();
            			cout<<"\t\t\t\t\t\t\t           Press Any Keys to Return to Main Menu";
            			getch();
            			system("cls");
            			cover();
						}
   					else
						if		(Player2score == c)
						{
         				system("cls");
							cout<<"\t\t\t\t\t\t\t\t\t     Congratulations " <<nama2<<"!"<<endl;
            			win();
            			cout<<"\t\t\t\t\t\t\t           Press Any Keys to Return to Main Menu";
            			getch();
            			system("cls");
                     cover();
						}
         			}
						while (Player1score != c && Player2score !=c);
						getch();
         			break;}
         case 3 : {system("cls");
         			cout<<"Cara bermain"<<endl;
         			cout<<"- Pilih pilihan suit yang Anda inginkan."<<endl;
                  cout<<"- 1 untuk memilih semut."<<endl;
                  cout<<"- 2 untuk memilih manusia."<<endl;
                  cout<<"- 3 untuk memilih gajah."<<endl;
                  cout<<" Semut menang melawan gajah, tetapi kalah melawan manusia."<<endl;
                  cout<<" Manusia menang melawan semut, tetapi kalah melawan gajah."<<endl;
                  cout<<" Gajah menang melawan manusia, tetapi kalah melawan semut."<<endl;
                  cout<<" Apabila player/CPU memenangi suit, maka player/CPU mendapat +1 Win."<<endl;
                  cout<<" CPU memenangi suit, maka win streak berakhir dan permainan selesai."<<endl;
         			int CPUnum,b,CPUscore=0,Humanscore=0;
						string Komputer,Human,nama;
						cout<<" Masukkan Nama Anda:";
						getline(cin,nama);
						do
						{
   						cout<<"Suit:";
  	 						cin>>b;
   						randomize();
   						CPUnum = random(3);
   						if (b == 1)
    								Human = "Semut";
      							else
   									if (b == 2)
    									Human = "Manusia";
      								else
   										if (b == 3)
      									Human = "Gajah";
   						if (CPUnum == 0)
    								Komputer = "Semut";
      							else
   									if (CPUnum == 1)
    									Komputer = "Manusia";
      								else
   										if (CPUnum == 2)
               						Komputer = "Gajah";
							cout<<Human<<"\t\t\t\t"<<"VS"<<"\t\t\t"<<Komputer<<endl;

   						if		(b == 1 && CPUnum == 0)
   								{  system("cls");
            						semutvssemut();
           						 	cout << "Ant meets another Ant, its a tie!" << endl;
                              Humanscore += 0;
            						CPUscore += 0;
            						cout <<nama<<"'s"<<" win streak: "<<Humanscore<<endl;
         						}
    								else
   						if		(b == 1 && CPUnum == 1)
   							  	{  system("cls");
            						semutvsmanusia();
         							cout << "Ant is stepped on by Human, CPU wins!" << endl;
            						Humanscore += 0;
            						CPUscore += 1;
            						cout <<nama<<"'s"<<" win streak: "<<Humanscore<<endl;
         						}
   								 else
   						if		(b == 1 && CPUnum == 2)
   								{  system("cls");
            						semutvsgajah();
         							cout << "Ant goes into elephant's ear!, "<<nama<<" wins!" << endl;
            						Humanscore += 1;
            						CPUscore += 0;
                              cout <<nama<<"'s"<<" win streak: "<<Humanscore<<endl;
            						cout <<"CPU's score: "<<CPUscore<<endl;

         						}
                            else
   						if		(b == 2 && CPUnum == 0)
   								{  system("cls");
                           	manusiavssemut();
         							cout << "Ant is stepped on by Human, "<<nama<<" wins!" << endl;
            						Humanscore += 1;
                              CPUscore += 0;
            						cout <<nama<<"'s"<<" win streak: "<<Humanscore<<endl;
            						cout <<"CPU's score: "<<CPUscore<<endl;
         						}
    								else
   						if		(b == 2 && CPUnum == 1)
   								{  system("cls");
            						manusiavsmanusia();
         						  	cout << "Human meets Human, its a tie!" << endl;
                              Humanscore += 0;
            						CPUscore += 0;
            						cout <<nama<<"'s"<<" win streak: "<<Humanscore<<endl;
            						cout <<"CPU's score: "<<CPUscore<<endl;
         						}
    								else
   						if		(b == 2 && CPUnum == 2)
    								{  system("cls");
         							manusiavsgajah();
         							cout << "Human is stepped on by elephant, CPU wins!" << endl;
            						Humanscore += 0;
            						CPUscore += 1;
            						cout <<nama<<"'s"<<" win streak: "<<Humanscore<<endl;
            						cout <<"CPU's score: "<<CPUscore<<endl;

         						}
    								else
   						if		(b == 3 && CPUnum == 0)
   								{	system("cls");
                           	gajahvssemut();
         							cout << "Ant goes into elephant's ear! CPU wins!" << endl;
                              Humanscore += 0;
            						CPUscore += 1;
            						cout <<nama<<"'s"<<" win streak: "<<Humanscore<<endl;
            						cout <<"CPU's score: "<<CPUscore<<endl;

         						}
                           else
         				if		(b == 3 && CPUnum == 1)
   							  	{  system("cls");
         							gajahvsmanusia();
         							cout << "Human is stepped on by elephant, "<<nama<<" wins!" << endl;
         							Humanscore += 1;
            						CPUscore += 0;
            						cout <<nama<<"'s"<<" win streak: "<<Humanscore<<endl;
            						cout <<"CPU's score: "<<CPUscore<<endl;
         						}
    								else
   						if		(b == 3 && CPUnum == 2)
   								{	system("cls");
            						gajahvsgajah();
         							cout << "Elephant meets elephant, its a tie!" << endl;
         							Humanscore += 0;
            						CPUscore +=0;
            						cout <<nama<<"'s"<<" win streak: "<<Humanscore<<endl;
            						cout <<"CPU's score: "<<CPUscore<<endl;
         						}
   						if		(CPUscore == 1)
									{
         							system("cls");
                              cout<<"\t\t\t\t\t\t\t\t\tYou Lose, Try again next time!"<<endl;
                              cout<<"\t\t\t\t\t\t\t\t\tWin Streak "<<": "<<Humanscore<<endl;
                              lose();
                              ofstream f1;
 										f1.open("NamaPemain.txt",ios::out|ios::ate);
 										if(!f1.fail())
                              {
                              f1<<nama<<"\t\t"<<Humanscore<<endl;
                              }
                              cout<<"\t\t\t\t\t\t\tPress any keys to see return to Main Menu and see the Scoreboard";
                              getch();
                              system("cls");
                              cover();
									}
                  }
						while (CPUscore != 1);
						getch();}break;
         case 4 : system("cls");
         			cover();
			default:	cout<<"Anda tidak memasukkan 1,2,3, atau 4"<<endl;
         		  	cout<<"Anda akan dialihkan ke menu utama,tekan sembarang tombol keyboard untuk melanjutkan"<<endl;
                 	getch();
                 	system("cls");
         		  	cover();
         }
         break;
case 2 : {system("cls");
			highscore();
			string line;
         ifstream lo;
         lo.open("NamaPemain.txt",ios::in);
         if (!lo.fail())
         {
         while ( getline (lo,line) )
         {
         cout<<"\t\t\t\t\t\t\t\t\t" << line << '\n';
         }
         lo.close();
         cout<<"\t\t\t\t\t\t\t\t  Press any keys to return to Main Menu";
         getch();
         }
         system("cls");
         cover();
         }
         break;
case 3  :exit(0);break;
default :system("cls");
         cover();
}
getch();
}

void main()
{
nuki();
system("cls");
cover();
system("cls");
getch();
}